real: promote 2.9.0 (#54)

diff --git a/docs/skeletons/task-generic/module-task b/docs/skeletons/task-generic/module-task
--- a/docs/skeletons/task-generic/module-task
+++ b/docs/skeletons/task-generic/module-task
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
-# template-task: 3.3.0
-#   template-task-base: 2.3.0
+# template-task-base: 2.3.1
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -17,30 +16,25 @@
 declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
 [[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
 # shellcheck disable=SC2015 source-path=SCRIPTDIR/..
-source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/X_MODULE_X-lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
-# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/X_MODULE_X.lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
+# shellcheck disable=SC2015 source-path=/opt/bl64
 source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }
 
 declare MY_COMMAND="$BL64_VAR_NULL"
 declare MY_OPTION=''
-# X_GLOBALS_PLACEHOLDER_X
 
 function my_X_COMMAND_X() {
-  bl64_dbg_app_show_function "$@"
-  # X_COMMAND_PLACEHOLDER_X
+  bl64_dbg_app_show_function
 }
 
 function my_initialize() {
   bl64_dbg_app_show_function
+  [[ -n "$MY_OPTION" && -n "$MY_COMMAND" ]] || { bl64_msg_help_show && return 1; }
   bl64_msg_show_about
-  # X_INIT_PARAMETER_PLACEHOLDER_X
-  [[ -n "$MY_OPTION" && -n "$MY_COMMAND" ]] &&
-    bl64_check_parameter 'MY_PARAMETERX' ||
-    { bl64_msg_help_show && return 1; }
-  s64_X_MODULE_X_lib_setup
-  # X_INIT_PARAMETER_PLACEHOLDER_X
-  # X_INIT_PLACEHOLDER_X
-  # X_INIT_INFO_PLACEHOLDER_X
+  s64_X_MODULE_X_lib_setup &&
+    bl64_check_parameter 'MY_PARAMETERX' &&
+    bl64_msg_show_setup "$BL64_VAR_DEFAULT" \
+      'X_PARAMETER_X'
 }
 
 bl64_lib_script_version_set '1.0.0'
@@ -53,11 +47,11 @@ bl64_msg_help_parameters_set \
 
 while getopts ':xV:D:h' MY_OPTION; do
   case "$MY_OPTION" in
-  x) MY_COMMAND='X_COMMAND_X' ;;
-  V) S64_CORE_SET_VERBOSE="$OPTARG" ;;
-  D) S64_CORE_SET_DEBUG="$OPTARG" ;;
-  h) bl64_msg_help_show && exit 0 ;;
-  *) bl64_msg_help_show && exit 1 ;;
+    x) MY_COMMAND='X_COMMAND_X' ;;
+    V) S64_CORE_SET_VERBOSE="$OPTARG" ;;
+    D) S64_CORE_SET_DEBUG="$OPTARG" ;;
+    h) bl64_msg_help_show && exit 0 ;;
+    *) bl64_msg_help_show && exit 1 ;;
   esac
 done
 bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && my_initialize || exit $?
diff --git a/src/k8s/k8s-object-show b/src/k8s/k8s-object-show
--- a/src/k8s/k8s-object-show
+++ b/src/k8s/k8s-object-show
@@ -16,13 +16,13 @@
 declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
 [[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
 # shellcheck disable=SC2015 source-path=SCRIPTDIR/..
-source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/k8s-lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
-# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/k8s.lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
+# shellcheck disable=SC2015 source-path=/opt/bl64
 source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }
 
-declare MY_NAMESPACE="${1:-$BL64_VAR_DEFAULT}"
-declare MY_TYPE="${2:-$BL64_VAR_DEFAULT}"
-declare MY_OBJECT="${3:-$BL64_VAR_DEFAULT}"
+declare MY_TYPE="${1:-$BL64_VAR_DEFAULT}"
+declare MY_OBJECT="${2:-$BL64_VAR_DEFAULT}"
+declare MY_NAMESPACE="${3:-$BL64_VAR_DEFAULT}"
 
 function my_get_type() {
   bl64_dbg_app_show_function
@@ -30,11 +30,10 @@ function my_get_type() {
   local object="$2"
 
   # shellcheck disable=SC2086,SC2046
-  bl64_k8s_run_kubectl \
-    "$BL64_VAR_DEFAULT" \
+  bl64_k8s_run_kubectl "$BL64_VAR_DEFAULT" \
     get \
     --output="$S64_K8S_OUTPUT_FORMAT" \
-  $(s64_k8s_lib_cli_set_ns "$MY_NAMESPACE") \
+    $(s64_k8s_lib_cli_set_ns "$MY_NAMESPACE") \
     "$type" $object
 }
 
@@ -44,8 +43,7 @@ function my_list() {
 
   bl64_lib_var_is_default "$MY_OBJECT" && MY_OBJECT=''
   if bl64_lib_var_is_default "$MY_TYPE"; then
-    MY_TYPE="$(bl64_k8s_run_kubectl \
-      "$BL64_VAR_DEFAULT" \
+    MY_TYPE="$(bl64_k8s_run_kubectl "$BL64_VAR_DEFAULT" \
       api-resources \
       --namespaced=true \
       --sort-by='name' \
@@ -65,11 +63,10 @@ function my_initialize() {
     bl64_msg_show_setup "$BL64_VAR_DEFAULT" \
       'MY_NAMESPACE' \
       'MY_TYPE' \
-      'MY_OBJECT' \
-      'S64_K8S_OUTPUT_FORMAT'
+      'MY_OBJECT'
 }
 
-bl64_lib_script_version_set '1.0.0'
+bl64_lib_script_version_set '2.0.0'
 bl64_msg_help_about_set 'Show deployed Kubernetes objects manifest'
 bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && my_initialize || exit $?
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
diff --git a/src/k8s/k8s-pod-run-shell b/src/k8s/k8s-pod-run-shell
--- a/src/k8s/k8s-pod-run-shell
+++ b/src/k8s/k8s-pod-run-shell
@@ -20,8 +20,8 @@
 declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
 [[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
 # shellcheck disable=SC2015 source-path=SCRIPTDIR/..
-source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/k8s-lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
-# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/k8s.lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
+# shellcheck disable=SC2015,SC2154 source-path=/opt/bl64
 source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }
 
 #
@@ -78,8 +78,7 @@ function my_shell_run() {
   }
   ' "$MY_POD_NAME" "$image" "$entrypoint" "$MY_CPU_REQUEST" "$MY_MEMORY_REQUEST" "$MY_CPU_LIMIT" "$MY_MEMORY_LIMIT"
 
-  bl64_k8s_run_kubectl \
-    "$BL64_VAR_DEFAULT" \
+  bl64_k8s_run_kubectl "$BL64_VAR_DEFAULT" \
     run \
     --attach \
     --rm \
@@ -96,8 +95,8 @@ function my_shell_run() {
 function my_initialize() {
   bl64_dbg_app_show_function
   [[ -n "$MY_OPTION" ]] || { bl64_msg_help_show && return 1; }
-  s64_k8s_lib_setup || 
-  return $?
+  s64_k8s_lib_setup ||
+    return $?
   [[ "$MY_CONTAINER_ENTRYPOINT" == "$BL64_VAR_DEFAULT" ]] && MY_CONTAINER_ENTRYPOINT='sh'
   [[ "$MY_CONTAINER_IMAGE" == "$BL64_VAR_DEFAULT" ]] && MY_CONTAINER_IMAGE='alpine'
   bl64_msg_show_about
@@ -131,14 +130,14 @@ bl64_msg_help_parameters_set \
 
 while getopts ':si:n:e:V:D:h' MY_OPTION; do
   case "$MY_OPTION" in
-  s) MY_COMMAND='shell_run' ;;
-  n) MY_NAMESPACE="$OPTARG" ;;
-  i) MY_CONTAINER_IMAGE="$OPTARG" ;;
-  e) MY_CONTAINER_ENTRYPOINT="$OPTARG" ;;
-  V) S64_CORE_SET_VERBOSE="$OPTARG" ;;
-  D) S64_CORE_SET_DEBUG="$OPTARG" ;;
-  h) bl64_msg_help_show && exit 0 ;;
-  *) bl64_msg_help_show && exit 1 ;;
+    s) MY_COMMAND='shell_run' ;;
+    n) MY_NAMESPACE="$OPTARG" ;;
+    i) MY_CONTAINER_IMAGE="$OPTARG" ;;
+    e) MY_CONTAINER_ENTRYPOINT="$OPTARG" ;;
+    V) S64_CORE_SET_VERBOSE="$OPTARG" ;;
+    D) S64_CORE_SET_DEBUG="$OPTARG" ;;
+    h) bl64_msg_help_show && exit 0 ;;
+    *) bl64_msg_help_show && exit 1 ;;
   esac
 done
 bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && my_initialize || exit $?
diff --git a/src/linux-package/linux-package-cleanup b/src/linux-package/linux-package-cleanup
--- a/src/linux-package/linux-package-cleanup
+++ b/src/linux-package/linux-package-cleanup
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# template-one: 3.0.0
+# template-one: 3.2.1
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -16,19 +16,18 @@
 declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
 [[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
 # shellcheck disable=SC2015 source-path=SCRIPTDIR/..
-source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/linux-lib" ||
-  { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
-# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/linux.lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
+# shellcheck disable=SC2015,SC2154 source-path=/opt/bl64
 source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }
 
-function cleanup_ubuntu() {
+function my_cleanup_ubuntu() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'auto-remove unused packages'
   bl64_pkg_cleanup &&
     bl64_pkg_run_apt autoremove "$BL64_PKG_SET_ASSUME_YES"
 }
 
-function cleanup_fedora() {
+function my_cleanup_fedora() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'auto-remove unused packages'
   bl64_pkg_cleanup &&
@@ -37,27 +36,29 @@ function cleanup_fedora() {
       autoremove
 }
 
-function cleanup() {
+function my_cleanup() {
   bl64_dbg_app_show_function
   bl64_ui_ask_confirmation 'Warning: the task will auto-cleanup packages' ||
     return $?
   case "$BL64_OS_DISTRO" in
-  ${BL64_OS_UB}-*) cleanup_ubuntu ;;
-  ${BL64_OS_FD}-*) cleanup_fedora ;;
-  *) bl64_check_alert_unsupported ;;
+    ${BL64_OS_UB}-*) cleanup_ubuntu ;;
+    ${BL64_OS_FD}-*) cleanup_fedora ;;
+    *) bl64_check_alert_unsupported ;;
   esac
 }
 
 function my_initialize() {
   bl64_dbg_app_show_function
+  bl64_msg_show_about
   bl64_check_privilege_root &&
     bl64_os_check_compatibility \
       "${BL64_OS_UB}" \
       "${BL64_OS_FD}"
 }
 
-bl64_lib_script_version_set '1.0.3'
+bl64_lib_script_version_set '1.0.4'
+bl64_msg_help_about_set 'Cleanup operating system packages'
 bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && my_initialize || exit $?
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
-cleanup
+my_cleanup
 bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
diff --git a/src/openssh/openssh-server-show b/src/openssh/openssh-server-show
--- a/src/openssh/openssh-server-show
+++ b/src/openssh/openssh-server-show
@@ -16,8 +16,8 @@
 declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
 [[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
 # shellcheck disable=SC2015 source-path=SCRIPTDIR/..
-source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/openssh-lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
-# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/openssh.lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
+# shellcheck disable=SC2015 source-path=/opt/bl64
 source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }
 
 function my_service_status_alpine() {
@@ -78,7 +78,7 @@ bl64_msg_help_about_set 'Show SSH server status'
 bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && my_initialize || exit $?
 bl64_msg_show_batch_status "$BL64_SCRIPT_ID"
 if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" ]]; then
-  source "${S64_CORE_PATH_ROOT}/core/linux-lib" &&
+  source "${S64_CORE_PATH_ROOT}/core/linux.lib" &&
     s64_linux_lib_setup
 fi &&
   my_service_status
diff --git a/src/pgsql/pgsql-query-show-active b/src/pgsql/pgsql-query-show-active
--- a/src/pgsql/pgsql-query-show-active
+++ b/src/pgsql/pgsql-query-show-active
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# template-one: 3.0.1
+# template-one: 3.2.1
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -16,26 +16,22 @@
 declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
 [[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
 # shellcheck disable=SC2015 source-path=SCRIPTDIR/..
-source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/pgsql-lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
-# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/pgsql.lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
+# shellcheck disable=SC2015,SC2154 source-path=/opt/bl64
 source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }
 
 export PGPASSWORD
-export PSQL_PAGER=''
 
 function my_initialize() {
   bl64_dbg_app_show_function
+  bl64_msg_show_about
+  PGPASSWORD="$S64_PGSQL_SERVER_PASSWORD"
   s64_psql_lib_setup &&
-    bl64_check_export 'S64_PGSQL_SERVER_PASSWORD' &&
-    PGPASSWORD="$S64_PGSQL_SERVER_PASSWORD" &&
-    bl64_msg_show_setup "$BL64_VAR_DEFAULT" \
-      'S64_PGSQL_SERVER_HOST' \
-      'S64_PGSQL_SERVER_PORT' \
-      'S64_PGSQL_SERVER_USER' \
-      'S64_PGSQL_DB_NAME'
+    bl64_check_export 'S64_PGSQL_SERVER_PASSWORD'
 }
 
-bl64_lib_script_version_set '2.0.1'
+bl64_lib_script_version_set '2.0.2'
+bl64_msg_help_about_set 'Show active queries'
 bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && my_initialize || exit $?
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 printf '
