feat: add lsusb (#18)

diff --git a/docs/skeletons/task-generic/module-task b/docs/skeletons/task-generic/module-task
--- a/docs/skeletons/task-generic/module-task
+++ b/docs/skeletons/task-generic/module-task
@@ -29,12 +29,9 @@
 
 declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
 # shellcheck source-path=SCRIPTDIR/..
-source "${S64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
-# shellcheck source-path=SCRIPTDIR/..
-source "${S64_CORE_PATH_ROOT}/X_MODULE_X/X_MODULE_X-lib" || { echo "Error: unable to load module library" && exit 1; }
+source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/X_MODULE_X-lib" || { echo "Error: unable to load module library" && exit 1; }
 # shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
-source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" ||
-  { echo "Error: unable to load bashlib64" && exit 1; }
+source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }
 
 #
 # Globals
@@ -54,7 +51,7 @@ function X_COMMAND_X() {
 function initialize() {
   bl64_dbg_app_show_function
 
-  bl64_check_parameter 'command' ||
+  bl64_check_parameter 'COMMAND' ||
     { help && return 1; }
 
   # optional # s64_X_MODULE_X_lib_setup || return $?
@@ -80,22 +77,21 @@ function help() {
 # Main
 #
 
-declare command="$BL64_VAR_NULL"
-declare option=''
+declare COMMAND="$BL64_VAR_NULL"
+declare OPTION=''
 
 (($# == 0)) && help && exit 1
-while getopts ':xV:D:h' option; do
-  case "$option" in
-  x) command='X_COMMAND_X' ;;
+while getopts ':xV:D:h' OPTION; do
+  case "$OPTION" in
+  x) COMMAND='X_COMMAND_X' ;;
   V) S64_CORE_SET_VERBOSE="$OPTARG" ;;
   D) S64_CORE_SET_DEBUG="$OPTARG" ;;
   h) help && exit 0 ;;
   *) help && exit 1 ;;
   esac
 done
-bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" || exit $?
-initialize || exit $?
+bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && initialize || exit $?
 
-bl64_msg_show_batch_start "${BL64_SCRIPT_ID}:$command"
-"${command}"
-bl64_msg_show_batch_finish $? "${BL64_SCRIPT_ID}:$command"
+bl64_msg_show_batch_start "${BL64_SCRIPT_ID}:$COMMAND"
+"${COMMAND}"
+bl64_msg_show_batch_finish $? "${BL64_SCRIPT_ID}:$COMMAND"
diff --git a/src/aws-eks/aws-eks-ami-show b/src/aws-eks/aws-eks-ami-show
--- a/src/aws-eks/aws-eks-ami-show
+++ b/src/aws-eks/aws-eks-ami-show
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
-# template: 1.0.0
+# template-task: 2.0.0
 #######################################
 # AWS EKS / AMI / Show
 #
-# Version: 1.0.2
+# Version: 1.1.0
 #
 #######################################
 # Copyright [2024] [serdigital64@gmail.com]
@@ -26,16 +26,10 @@
 #
 
 declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
-# shellcheck source-path=SCRIPTDIR/..
-source "${S64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
-# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
-source "${S64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-module-fs.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-module-aws.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo "Error: unable to load bashlib64" && exit 1; }
-# shellcheck source-path=SCRIPTDIR/..
-source "${S64_CORE_PATH_ROOT}/aws/aws-lib" || { echo "Error: unable to load module library" && exit 1; }
+# shellcheck disable=SC2015 source-path=SCRIPTDIR/..
+source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/aws-lib" || { echo "Error: unable to load module library" && exit 1; }
+# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }
 
 #
 # Functions
@@ -60,11 +54,8 @@ function show_recommended() {
 }
 
 function initialize() {
-  bl64_dbg_app_show_function "$@"
-  # shellcheck disable=SC2034
-  local command="$1"
-
-  bl64_check_parameter 'command' ||
+  bl64_dbg_app_show_function
+  bl64_check_parameter 'COMMAND' ||
     { help && return 1; }
   s64_aws_lib_setup
 }
@@ -89,26 +80,25 @@ function help() {
 # Main
 #
 
-declare command="$BL64_VAR_NULL"
-declare option=''
-declare ami_family='AL2023'
-declare k8s_version='1.29'
+declare COMMAND="$BL64_VAR_NULL"
+declare OPTION=''
+declare AMI_FAMILY='AL2023'
+declare K8S_VERSION='1.29'
 
 (($# == 0)) && help && exit 1
-while getopts ':la:r:V:D:h' option; do
-  case "$option" in
-  l) command='show_recommended' ;;
-  a) ami_family="$OPTARG" ;;
-  r) k8s_version="$OPTARG" ;;
+while getopts ':la:r:V:D:h' OPTION; do
+  case "$OPTION" in
+  l) COMMAND='show_recommended' ;;
+  a) AMI_FAMILY="$OPTARG" ;;
+  r) K8S_VERSION="$OPTARG" ;;
   V) S64_CORE_SET_VERBOSE="$OPTARG" ;;
   D) S64_CORE_SET_DEBUG="$OPTARG" ;;
   h) help && exit 0 ;;
   *) help && exit 1 ;;
   esac
 done
-bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" || exit $?
-initialize "$command" || exit $?
+bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && initialize || exit $?
 
-bl64_msg_show_batch_start "$command"
-"${command}" "$ami_family" "$k8s_version"
-bl64_msg_show_batch_finish $? "$command"
+bl64_msg_show_batch_start "${BL64_SCRIPT_ID}:$COMMAND"
+"${COMMAND}" "$AMI_FAMILY" "$K8S_VERSION"
+bl64_msg_show_batch_finish $? "${BL64_SCRIPT_ID}:$COMMAND"
diff --git a/src/core/git-lib b/src/core/git-lib
--- a/src/core/git-lib
+++ b/src/core/git-lib
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 # template-module-lib: 2.0.0
 #######################################
-# K8S / Lib
+# GIT / Lib
 #
 # Version: 2.0.0
 #
@@ -25,39 +25,22 @@
 # Imports
 #
 
-# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
-source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-module-k8s.bash" ||
-  { echo "Error: unable to load bashlib64" && exit 1; }
+# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_BL64}/bashlib64-module-xsv.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-fs.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-rxtx.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-api.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-vcs.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" ||
+  { echo 'Error: unable to load bashlib64' && exit 1; }
 
 #
 # Functions
 #
 
-function s64_k8s_lib_setup() {
+function s64_git_lib_setup() {
   bl64_dbg_app_show_function
-
-  bl64_k8s_setup
-}
-
-function s64_k8s_lib_cli_set_ns() {
-  bl64_dbg_app_show_function "$@"
-  local namespace="$1"
-  # shellcheck disable=SC2154
-  if [[ "$namespace" == "$BL64_VAR_DEFAULT" ]]; then
-    printf -- '--all-namespaces'
-  else
-    printf -- '--namespace %s' "${namespace}"
-  fi
-}
-
-function s64_k8s_lib_cli_set_output() {
-  bl64_dbg_app_show_function "$@"
-  local expand="$1"
-  # shellcheck disable=SC2154
-  case "$expand" in
-  "$BL64_VAR_DEFAULT") printf -- '' ;;
-  'json') printf -- '--output json' ;;
-  *) printf -- '' ;;
-  esac
 }
diff --git a/src/core/github-lib b/src/core/github-lib
--- a/src/core/github-lib
+++ b/src/core/github-lib
@@ -1,11 +1,9 @@
 #!/usr/bin/env bash
-# template: 1.1.0
-# template-module-setup: 1.1.0
-# template-module-cli: 1.1.0
+# template-module-lib: 2.0.0
 #######################################
 # GitHub / Lib
 #
-# Version: 1.0.2
+# Version: 2.0.0
 #
 #######################################
 # Copyright [2024] [serdigital64@gmail.com]
@@ -24,12 +22,22 @@
 #######################################
 
 #
+# Imports
+#
+
+# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" ||
+  { echo 'Error: unable to load bashlib64' && exit 1; }
+
+#
 # Globals
 #
 
 # shellcheck disable=SC2034
 {
   declare S64_GITHUB_PATH_CLI="${S64_GITHUB_PATH_CLI:-}"
+
+  export GH_VERBOSE
 }
 
 #
@@ -38,28 +46,22 @@
 
 function s64_github_lib_setup() {
   bl64_dbg_app_show_function
-  local command='gh'
   if [[ -z "$S64_GITHUB_PATH_CLI" ]]; then
-    if [[ -x "/home/linuxbrew/.linuxbrew/bin/${command}" ]]; then
-      S64_GITHUB_PATH_CLI="/home/linuxbrew/.linuxbrew/bin/${command}"
-    elif [[ -x "/opt/homebrew/bin/${command}" ]]; then
-      S64_GITHUB_PATH_CLI="/opt/homebrew/bin/${command}"
-    elif [[ -x "/usr/local/bin/${command}" ]]; then
-      S64_GITHUB_PATH_CLI="/usr/local/bin/${command}"
-    elif [[ -x "/usr/bin/${command}" ]]; then
-      S64_GITHUB_PATH_CLI="/usr/bin/${command}"
-    else
-      bl64_check_alert_resource_not_found "$command"
-      return $?
-    fi
+    S64_GITHUB_PATH_CLI="$(bl64_bsh_command_locate 'gh')"
   else
     bl64_check_command "$S64_GITHUB_PATH_CLI" ||
       return $?
   fi
 }
 
+function s64_github_lib_reset() {
+  bl64_dbg_app_show_function
+  unset GH_VERBOSE
+}
+
 function s64_github_lib_run_gh() {
   bl64_dbg_app_show_function "$@"
+  s64_github_lib_reset
   bl64_msg_app_verbose_enabled && GH_VERBOSE='1'
   bl64_dbg_app_trace_start
   # shellcheck disable=SC2086
diff --git a/src/core/kind-lib b/src/core/kind-lib
--- a/src/core/kind-lib
+++ b/src/core/kind-lib
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
-# template: 1.0.0
+# template-module-lib: 2.0.0
 #######################################
 # Kind / Lib
 #
-# Version: 1.0.0
+# Version: 2.0.0
 #
 #######################################
 # Copyright [2024] [serdigital64@gmail.com]
@@ -20,6 +20,21 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #######################################
+
+#
+# Imports
+#
+
+# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_BL64}/bashlib64-module-fs.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-xsv.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-cnt.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-ui.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" ||
+  { echo 'Error: unable to load bashlib64' && exit 1; }
 
 #
 # Globals
@@ -40,19 +55,12 @@
 
 function s64_kind_lib_setup() {
   bl64_dbg_app_show_function
+  bl64_cnt_setup &&
+    bl64_k8s_setup ||
+    return $?
+
   if [[ -z "$S64_KIND_PATH_CLI" ]]; then
-    if [[ -x '/home/linuxbrew/.linuxbrew/bin/kind' ]]; then
-      S64_KIND_PATH_CLI='/home/linuxbrew/.linuxbrew/bin/kind'
-    elif [[ -x '/opt/homebrew/bin/kind' ]]; then
-      S64_KIND_PATH_CLI='/opt/homebrew/bin/kind'
-    elif [[ -x '/usr/local/bin/kind' ]]; then
-      S64_KIND_PATH_CLI='/usr/local/bin/kind'
-    elif [[ -x '/usr/bin/kind' ]]; then
-      S64_KIND_PATH_CLI='/usr/bin/kind'
-    else
-      bl64_check_alert_resource_not_found 'kind'
-      return $?
-    fi
+    S64_KIND_PATH_CLI="$(bl64_bsh_command_locate 'kind')"
   else
     bl64_check_command "$S64_KIND_PATH_CLI" ||
       return $?
diff --git a/src/core/linux-lib b/src/core/linux-lib
--- a/src/core/linux-lib
+++ b/src/core/linux-lib
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
-# template: 1.0.0
+# template-module-lib: 2.0.0
 #######################################
 # Linux / Lib
 #
-# Version: 1.3.0
+# Version: 2.0.0
 #
 #######################################
 # Copyright [2024] [serdigital64@gmail.com]
@@ -22,6 +22,25 @@
 #######################################
 
 #
+# Imports
+#
+
+# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_BL64}/bashlib64-module-ui.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-xsv.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-cryp.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-api.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-vcs.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-rxtx.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-fs.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-pkg.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" ||
+  { echo 'Error: unable to load bashlib64' && exit 1; }
+
+#
 # Globals
 #
 
@@ -33,6 +52,7 @@
   declare S64_LINUX_PATH_CLI_FSCK=''
   declare S64_LINUX_PATH_CLI_JOURNALCTL=''
   declare S64_LINUX_PATH_CLI_LSBLK=''
+  declare S64_LINUX_PATH_CLI_LSUSB=''
   declare S64_LINUX_PATH_CLI_LVS=''
   declare S64_LINUX_PATH_CLI_MDADM=''
   declare S64_LINUX_PATH_CLI_MKFS=''
@@ -56,6 +76,7 @@ function s64_linux_lib_setup() {
     S64_LINUX_PATH_CLI_FSCK='/usr/sbin/fsck'
     S64_LINUX_PATH_CLI_JOURNALCTL='/usr/bin/journalctl'
     S64_LINUX_PATH_CLI_LSBLK='/bin/lsblk'
+    S64_LINUX_PATH_CLI_LSUSB='/bin/lsusb'
     S64_LINUX_PATH_CLI_LVS='/usr/sbin/lvs'
     S64_LINUX_PATH_CLI_MDADM='/usr/sbin/mdadm'
     S64_LINUX_PATH_CLI_MKFS='/usr/sbin/mkfs'
@@ -70,6 +91,7 @@ function s64_linux_lib_setup() {
     S64_LINUX_PATH_CLI_FSCK='/usr/sbin/fsck'
     S64_LINUX_PATH_CLI_JOURNALCTL='/usr/bin/journalctl'
     S64_LINUX_PATH_CLI_LSBLK='/usr/bin/lsblk'
+    S64_LINUX_PATH_CLI_LSUSB='/usr/bin/lsusb'
     S64_LINUX_PATH_CLI_LVS='/usr/sbin/lvs'
     S64_LINUX_PATH_CLI_MDADM='/usr/sbin/mdadm'
     S64_LINUX_PATH_CLI_MKFS='/usr/sbin/mkfs'
@@ -220,6 +242,20 @@ function s64_linux_lib_run_mkfs() {
   bl64_dbg_app_trace_start
   # shellcheck disable=SC2086
   "$S64_LINUX_PATH_CLI_MKFS" \
+    $verbose_flag \
+    "$@"
+  bl64_dbg_app_trace_stop
+}
+
+function s64_linux_lib_run_lsusb() {
+  bl64_dbg_app_show_function "$@"
+  local verbose_flag='--verbose'
+  bl64_msg_app_verbose_enabled || verbose_flag=' '
+  bl64_check_command "$S64_LINUX_PATH_CLI_LSUSB" ||
+    return $?
+  bl64_dbg_app_trace_start
+  # shellcheck disable=SC2086
+  "$S64_LINUX_PATH_CLI_LSUSB" \
     $verbose_flag \
     "$@"
   bl64_dbg_app_trace_stop
diff --git a/src/core/openssh-lib b/src/core/openssh-lib
--- a/src/core/openssh-lib
+++ b/src/core/openssh-lib
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
-# template: 1.0.0
+# template-module-lib: 2.0.0
 #######################################
 # OpenSSH / Lib
 #
-# Version: 1.0.0
+# Version: 2.0.0
 #
 #######################################
 # Copyright [2024] [serdigital64@gmail.com]
@@ -22,6 +22,14 @@
 #######################################
 
 #
+# Imports
+#
+
+# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" ||
+  { echo 'Error: unable to load bashlib64' && exit 1; }
+
+#
 # Globals
 #
 
@@ -38,18 +46,7 @@ function s64_openssh_lib_setup() {
   bl64_dbg_app_show_function
   local command='ssh-keygen'
   if [[ -z "$S64_OPENSSH_PATH_SSH_KEYGEN" ]]; then
-    if [[ -x "/home/linuxbrew/.linuxbrew/bin/${command}" ]]; then
-      S64_OPENSSH_PATH_SSH_KEYGEN="/home/linuxbrew/.linuxbrew/bin/${command}"
-    elif [[ -x "/opt/homebrew/bin/${command}" ]]; then
-      S64_OPENSSH_PATH_SSH_KEYGEN="/opt/homebrew/bin/${command}"
-    elif [[ -x "/usr/local/bin/${command}" ]]; then
-      S64_OPENSSH_PATH_SSH_KEYGEN="/usr/local/bin/${command}"
-    elif [[ -x "/usr/bin/${command}" ]]; then
-      S64_OPENSSH_PATH_SSH_KEYGEN="/usr/bin/${command}"
-    else
-      bl64_check_alert_resource_not_found 'ssh-keygen'
-      return $?
-    fi
+    S64_OPENSSH_PATH_SSH_KEYGEN="$(bl64_bsh_command_locate 'ssh-keygen')"
   else
     bl64_check_command "$S64_OPENSSH_PATH_SSH_KEYGEN" ||
       return $?
diff --git a/src/core/pgsql-lib b/src/core/pgsql-lib
--- a/src/core/pgsql-lib
+++ b/src/core/pgsql-lib
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
-# template: 1.0.0
+# template-module-lib: 2.0.0
 #######################################
 # PGSQL / Lib
 #
-# Version: 1.1.1
+# Version: 2.0.0
 #
 #######################################
 # Copyright [2024] [serdigital64@gmail.com]
@@ -20,6 +20,20 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #######################################
+
+#
+# Imports
+#
+
+# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_BL64}/bashlib64-module-fs.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-xsv.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-cnt.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" ||
+  { echo 'Error: unable to load bashlib64' && exit 1; }
 
 #
 # Globals
@@ -41,18 +55,7 @@
 function s64_psql_lib_setup() {
   bl64_dbg_app_show_function
   if [[ -z "$S64_PGSQL_PATH_CLI" ]]; then
-    if [[ -x '/home/linuxbrew/.linuxbrew/bin/psql' ]]; then
-      S64_PGSQL_PATH_CLI='/home/linuxbrew/.linuxbrew/bin/psql'
-    elif [[ -x '/opt/homebrew/bin/psql' ]]; then
-      S64_PGSQL_PATH_CLI='/opt/homebrew/bin/psql'
-    elif [[ -x '/usr/local/bin/psql' ]]; then
-      S64_PGSQL_PATH_CLI='/usr/local/bin/psql'
-    elif [[ -x '/usr/bin/psql' ]]; then
-      S64_PGSQL_PATH_CLI='/usr/bin/psql'
-    else
-      bl64_check_alert_resource_not_found 'psql'
-      return $?
-    fi
+    S64_PGSQL_PATH_CLI="$(bl64_bsh_command_locate 'psql')"
   else
     bl64_check_command "$S64_PGSQL_PATH_CLI"
   fi
diff --git a/src/core/restic-lib b/src/core/restic-lib
--- a/src/core/restic-lib
+++ b/src/core/restic-lib
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
-# template: 1.0.0
+# template-module-lib: 2.0.0
 #######################################
 # Restic / Lib
 #
-# Version: 1.1.0
+# Version: 2.0.0
 #
 #######################################
 # Copyright [2024] [serdigital64@gmail.com]
@@ -22,6 +22,14 @@
 #######################################
 
 #
+# Imports
+#
+
+# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" ||
+  { echo 'Error: unable to load bashlib64' && exit 1; }
+
+#
 # Globals
 #
 
@@ -30,6 +38,7 @@
   declare S64_RESTIC_PATH_CLI="${S64_RESTIC_PATH_CLI:-}"
   declare S64_RESTIC_PATH_REPOSITORY="${S64_RESTIC_PATH_REPOSITORY:-}"
   declare S64_RESTIC_PASSWORD="${S64_RESTIC_PASSWORD:-}"
+
   export RESTIC_REPOSITORY=''
   export RESTIC_PASSWORD=''
 }
@@ -41,18 +50,7 @@
 function s64_restic_lib_setup() {
   bl64_dbg_app_show_function
   if [[ -z "$S64_RESTIC_PATH_CLI" ]]; then
-    if [[ -x '/home/linuxbrew/.linuxbrew/bin/restic' ]]; then
-      S64_RESTIC_PATH_CLI='/home/linuxbrew/.linuxbrew/bin/restic'
-    elif [[ -x '/opt/homebrew/bin/restic' ]]; then
-      S64_RESTIC_PATH_CLI='/opt/homebrew/bin/restic'
-    elif [[ -x '/usr/local/bin/restic' ]]; then
-      S64_RESTIC_PATH_CLI='/usr/local/bin/restic'
-    elif [[ -x '/usr/bin/restic' ]]; then
-      S64_RESTIC_PATH_CLI='/usr/bin/restic'
-    else
-      bl64_check_alert_resource_not_found 'restic'
-      return $?
-    fi
+    S64_RESTIC_PATH_CLI="$(bl64_bsh_command_locate 'restic')"
   else
     bl64_check_command "$S64_RESTIC_PATH_CLI" ||
       return $?
diff --git a/src/core/rsync-lib b/src/core/rsync-lib
--- a/src/core/rsync-lib
+++ b/src/core/rsync-lib
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
-# template: 1.0.0
+# template-module-lib: 2.0.0
 #######################################
 # RSync / Lib
 #
-# Version: 1.1.0
+# Version: 2.0.0
 #
 #######################################
 # Copyright [2024] [serdigital64@gmail.com]
@@ -20,6 +20,15 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #######################################
+
+#
+# Imports
+#
+
+# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_BL64}/bashlib64-module-ui.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" ||
+  { echo 'Error: unable to load bashlib64' && exit 1; }
 
 #
 # Globals
@@ -51,21 +60,9 @@
 function s64_rsync_lib_setup() {
   bl64_dbg_app_show_function
   if [[ -z "$S64_RSYNC_PATH_CLI" ]]; then
-    if [[ -x '/home/linuxbrew/.linuxbrew/bin/rsync' ]]; then
-      S64_RSYNC_PATH_CLI='/home/linuxbrew/.linuxbrew/bin/rsync'
-    elif [[ -x '/opt/homebrew/bin/rsync' ]]; then
-      S64_RSYNC_PATH_CLI='/opt/homebrew/bin/rsync'
-    elif [[ -x '/usr/local/bin/rsync' ]]; then
-      S64_RSYNC_PATH_CLI='/usr/local/bin/rsync'
-    elif [[ -x '/usr/bin/rsync' ]]; then
-      S64_RSYNC_PATH_CLI='/usr/bin/rsync'
-    else
-      bl64_check_alert_resource_not_found 'rsync'
-      return $?
-    fi
+    S64_RSYNC_PATH_CLI="$(bl64_bsh_command_locate 'rsync')"
   else
-    bl64_check_command "$S64_RSYNC_PATH_CLI" ||
-      return $?
+    bl64_check_command "$S64_RSYNC_PATH_CLI"
   fi
 }
 
diff --git a/src/core/trivy-lib b/src/core/trivy-lib
--- a/src/core/trivy-lib
+++ b/src/core/trivy-lib
@@ -1,12 +1,9 @@
 #!/usr/bin/env bash
-# template: 1.1.0
-# template-module-setup: 1.1.0
-# template-module-cli: 1.1.0
-# template-module-vars: 1.0.0
+# template-module-lib: 2.0.0
 #######################################
 # Trivy / Lib
 #
-# Version: 1.0.0
+# Version: 2.0.0
 #
 #######################################
 # Copyright [2024] [serdigital64@gmail.com]
@@ -23,6 +20,14 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #######################################
+
+#
+# Imports
+#
+
+# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" ||
+  { echo 'Error: unable to load bashlib64' && exit 1; }
 
 #
 # Globals
@@ -42,23 +47,10 @@
 
 function s64_trivy_lib_setup() {
   bl64_dbg_app_show_function
-  local command='trivy'
   if [[ -z "$S64_TRIVY_PATH_CLI" ]]; then
-    if [[ -x "/home/linuxbrew/.linuxbrew/bin/${command}" ]]; then
-      S64_TRIVY_PATH_CLI="/home/linuxbrew/.linuxbrew/bin/${command}"
-    elif [[ -x "/opt/homebrew/bin/${command}" ]]; then
-      S64_TRIVY_PATH_CLI="/opt/homebrew/bin/${command}"
-    elif [[ -x "/usr/local/bin/${command}" ]]; then
-      S64_TRIVY_PATH_CLI="/usr/local/bin/${command}"
-    elif [[ -x "/usr/bin/${command}" ]]; then
-      S64_TRIVY_PATH_CLI="/usr/bin/${command}"
-    else
-      bl64_check_alert_resource_not_found "$command"
-      return $?
-    fi
+    S64_TRIVY_PATH_CLI="$(bl64_bsh_command_locate 'trivy')"
   else
-    bl64_check_command "$S64_TRIVY_PATH_CLI" ||
-      return $?
+    bl64_check_command "$S64_TRIVY_PATH_CLI"
   fi
 }
 
diff --git a/src/linux-distro/linux-distro-upgrade b/src/linux-distro/linux-distro-upgrade
--- a/src/linux-distro/linux-distro-upgrade
+++ b/src/linux-distro/linux-distro-upgrade
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# template: 1.0.0
+# template-one: 2.0.0
 # template-import: 1.0.0
 #######################################
 # Linux / Distro / Upgrade
@@ -27,30 +27,16 @@
 #
 
 declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
-# shellcheck source-path=SCRIPTDIR/..
-source "${S64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
-# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
-source "${S64_CORE_PATH_BL64}/bashlib64-module-ui.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-module-xsv.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-module-cryp.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-module-api.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-module-vcs.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-module-rxtx.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-module-fs.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-module-pkg.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" ||
-  { echo "Error: unable to load bashlib64" && exit 1; }
-# shellcheck source-path=SCRIPTDIR/..
-source "${S64_CORE_PATH_ROOT}/linux/linux-lib" || { echo "Error: unable to load module library" && exit 1; }
+# shellcheck disable=SC2015 source-path=SCRIPTDIR/..
+source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/linux-lib" || { echo "Error: unable to load module library" && exit 1; }
+# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }
 
 #
 # Globals
 #
 
-# Distro dependant upgrade command
+# Distro dependant upgrade COMMAND
 declare _S64_LINUX_DISTRO_DO_RELEASE_UPGRADE=''
 
 #
@@ -120,27 +106,26 @@ function upgrade() {
   bl64_ui_ask_confirmation 'Warning: the task will perform unattended OS upgrade to the next available distro release' ||
     return $?
   case "$BL64_OS_DISTRO" in
-  ${BL64_OS_UB}-*) upgrade_ubuntu;;
+  ${BL64_OS_UB}-*) upgrade_ubuntu ;;
   ${BL64_OS_FD}-*) upgrade_fedora "$release" ;;
   *) bl64_check_alert_unsupported ;;
   esac
 }
 
 function initialize() {
-  bl64_dbg_app_show_function "$@"
-  # shellcheck disable=SC2034
-  local command="$1"
+  bl64_dbg_app_show_function
 
-  bl64_check_parameter 'command' ||
+  bl64_check_parameter 'COMMAND' ||
     { help && return 1; }
 
   bl64_check_privilege_root &&
     bl64_os_check_compatibility \
       "${BL64_OS_UB}-23" \
-      "${BL64_OS_FD}-39" ||
+      "${BL64_OS_FD}-39" &&
+    s64_linux_lib_setup ||
     return $?
 
-  if [[ "$command" == 'upgrade' ]]; then
+  if [[ "$BL64_SCRIPT_ID" == 'upgrade' ]]; then
     case "$BL64_OS_DISTRO" in
     ${BL64_OS_UB}-*)
       _S64_LINUX_DISTRO_DO_RELEASE_UPGRADE='/bin/do-release-upgrade'
@@ -171,27 +156,25 @@ function help() {
 # Main
 #
 
-declare command="$BL64_VAR_NULL"
-declare debug="$BL64_DBG_TARGET_NONE"
-declare option=''
-declare verbose="$BL64_MSG_VERBOSE_ALL"
-declare release="$BL64_VAR_NULL"
+declare COMMAND="$BL64_VAR_NULL"
+declare OPTION=''
+declare RELEASE="$BL64_VAR_NULL"
 
 (($# == 0)) && help && exit 1
-while getopts ':pur:V:D:h' option; do
-  case "$option" in
-  p) command='prepare' ;;
-  u) command='upgrade' ;;
-  r) release="$OPTARG" ;;
-  V) verbose="$OPTARG" ;;
-  D) debug="$OPTARG" ;;
+while getopts ':pur:V:D:h' OPTION; do
+  case "$OPTION" in
+  p) COMMAND='prepare' ;;
+  u) COMMAND='upgrade' ;;
+  r) RELEASE="$OPTARG" ;;
+  V) S64_CORE_SET_VERBOSE="$OPTARG" ;;
+  D) S64_CORE_SET_DEBUG="$OPTARG" ;;
   h) help && exit 0 ;;
   *) help && exit 1 ;;
   esac
 done
 bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" || exit $?
-initialize "$command" || exit $?
+initialize "$BL64_SCRIPT_ID" || exit $?
 
-bl64_msg_show_batch_start "$command"
-"${command}" "$release"
-bl64_msg_show_batch_finish $? "$command"
+bl64_msg_show_batch_start "${BL64_SCRIPT_ID}:$COMMAND"
+"${COMMAND}" "$RELEASE"
+bl64_msg_show_batch_finish $? "${BL64_SCRIPT_ID}:$COMMAND"
diff --git a/src/pgsql/pgsql-index-info b/src/pgsql/pgsql-index-info
--- a/src/pgsql/pgsql-index-info
+++ b/src/pgsql/pgsql-index-info
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
-# template: 1.0.0
+# template-task: 2.0.0
 #######################################
 # PGSQL / Index / Info
 #
-# Version: 1.0.0
+# Version: 1.0.1
 #
 #######################################
 # Copyright [2024] [serdigital64@gmail.com]
@@ -26,12 +26,11 @@
 #
 
 declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
-# shellcheck source-path=SCRIPTDIR/..
-source "${S64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
-# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
-source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo "Error: unable to load bashlib64" && exit 1; }
-# shellcheck source-path=SCRIPTDIR/..
-source "${S64_CORE_PATH_ROOT}/pgsql/pgsql-lib" || { echo "Error: unable to load module library" && exit 1; }
+# shellcheck disable=SC2015 source-path=SCRIPTDIR/..
+source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/pgsql-lib" || { echo "Error: unable to load module library" && exit 1; }
+# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }
+
 
 #
 # Globals
@@ -52,7 +51,7 @@ function list() {
     --port="$S64_PGSQL_SERVER_PORT" \
     --dbname="$S64_PGSQL_DB_NAME" \
     --username="$S64_PGSQL_SERVER_USER" \
-    --command="\\di"
+    --COMMAND="\\di"
 }
 
 function describe() {
@@ -63,7 +62,7 @@ function describe() {
     --port="$S64_PGSQL_SERVER_PORT" \
     --dbname="$S64_PGSQL_DB_NAME" \
     --username="$S64_PGSQL_SERVER_USER" \
-    --command="\\d $index"
+    --COMMAND="\\d $index"
 }
 
 function check() {
@@ -84,19 +83,16 @@ FROM
 }
 
 function initialize() {
-  bl64_dbg_app_show_function "$@"
-  # shellcheck disable=SC2034
-  local command="$1"
-  local index="$2"
+  bl64_dbg_app_show_function
 
-  bl64_check_parameter 'command' ||
+  bl64_check_parameter 'COMMAND' ||
     { help && return 1; }
 
   s64_psql_lib_setup &&
     bl64_check_export 'S64_PGSQL_SERVER_PASSWORD' ||
     return $?
 
-  if [[ "$command" == 'describe' ]]; then
+  if [[ "${BL64_SCRIPT_ID}:$COMMAND" == 'describe' ]]; then
     bl64_check_parameter 'index' ||
       return $?
   fi
@@ -129,32 +125,29 @@ function help() {
 # Main
 #
 
-declare command="$BL64_VAR_NULL"
-declare debug="$BL64_DBG_TARGET_NONE"
-declare option=''
-declare verbose="$BL64_MSG_VERBOSE_ALL"
-declare index="$BL64_VAR_DEFAULT"
+declare COMMAND="$BL64_VAR_NULL"
+declare OPTION=''
+declare INDEX_NAME="$BL64_VAR_DEFAULT"
 
 (($# == 0)) && help && exit 1
-while getopts ':leko:p:u:b:x:V:D:h' option; do
-  case "$option" in
-  l) command='list' ;;
-  e) command='describe' ;;
-  k) command='check' ;;
+while getopts ':leko:p:u:b:x:V:D:h' OPTION; do
+  case "$OPTION" in
+  l) COMMAND='list' ;;
+  e) COMMAND='describe' ;;
+  k) COMMAND='check' ;;
   o) S64_PGSQL_SERVER_HOST="$OPTARG" ;;
   p) S64_PGSQL_SERVER_PORT="$OPTARG" ;;
   u) S64_PGSQL_SERVER_USER="$OPTARG" ;;
   b) S64_PGSQL_DB_NAME="$OPTARG" ;;
-  x) index="$OPTARG" ;;
-  V) verbose="$OPTARG" ;;
-  D) debug="$OPTARG" ;;
+  x) INDEX_NAME="$OPTARG" ;;
+  V) S64_CORE_SET_VERBOSE="$OPTARG" ;;
+  D) S64_CORE_SET_DEBUG="$OPTARG" ;;
   h) help && exit 0 ;;
   *) help && exit 1 ;;
   esac
 done
-bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" || exit $?
-initialize "$command" "$index" || exit $?
+bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && initialize || exit $?
 
-bl64_msg_show_batch_start "$command"
-"${command}" "$index"
-bl64_msg_show_batch_finish $? "$command"
+bl64_msg_show_batch_start "${BL64_SCRIPT_ID}:$COMMAND"
+"${COMMAND}" "$INDEX_NAME"
+bl64_msg_show_batch_finish $? "${BL64_SCRIPT_ID}:$COMMAND"
