feat: add modules (#14)

diff --git a/docs/skeletons/task-generic/module-task b/docs/skeletons/task-generic/module-task
--- a/docs/skeletons/task-generic/module-task
+++ b/docs/skeletons/task-generic/module-task
@@ -2,7 +2,7 @@
 # template: 1.0.0
 # template-import: 1.0.0
 #######################################
-# X_MODULE_X / [X_SUBMODULE_X /] X_APP_NAME_X
+# X_MODULE_NAME_X / [X_SUBMODULE_NAME_X /] X_APP_NAME_X
 #
 # Version: 1.0.0
 #
@@ -26,7 +26,14 @@
 # Imports
 #
 
-# X_IMPORTS_PLACEHOLDER_X
+declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
+# shellcheck source-path=SCRIPTDIR/..
+source "${S64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
+# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" ||
+  { echo "Error: unable to load bashlib64" && exit 1; }
+# shellcheck source-path=SCRIPTDIR/..
+source "${S64_CORE_PATH_ROOT}/X_MODULE_X/X_MODULE_X-lib" || { echo "Error: unable to load module library" && exit 1; }
 
 #
 # Globals
@@ -51,6 +58,7 @@ function initialize() {
   bl64_check_parameter 'command' ||
     { help && return 1; }
 
+  # optional # s64_X_MODULE_X_lib_setup || return $?
   # X_INIT_PLACEHOLDER_X
   return 0
 }
@@ -58,7 +66,7 @@ function initialize() {
 function help() {
   bl64_msg_show_usage \
     '-x [-V Verbose] [-D Debug] [-h]' \
-    'X_MODULE_X / [X_SUBMODULE_X /] X_APP_NAME_X' \
+    'X_MODULE_NAME_X / [X_SUBMODULE_NAME_X /] X_APP_NAME_X' \
     '
     -x         : X_COMMAND_INFO_X
     ' '
@@ -88,7 +96,7 @@ while getopts ':xV:D:h' option; do
   *) help && exit 1 ;;
   esac
 done
-bl64_dbg_set_level "$SYSOP64_CORE_SET_DEBUG" && bl64_msg_set_level "$SYSOP64_CORE_SET_VERBOSE" || exit $?
+bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" || exit $?
 initialize "$command" || exit $?
 
 bl64_msg_show_batch_start "$command"
diff --git a/src/github-repo/github-repo-show b/src/github-repo/github-repo-show
--- a/src/github-repo/github-repo-show
+++ b/src/github-repo/github-repo-show
@@ -25,13 +25,13 @@
 # Imports
 #
 
-declare SYSOP64_CORE_PATH_ROOT="${SYSOP64_CORE_PATH_ROOT:-/opt/sysop64}"
+declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
 # shellcheck source-path=SCRIPTDIR/..
-source "${SYSOP64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
+source "${S64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
 # shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
-source "${SYSOP64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo "Error: unable to load bashlib64" && exit 1; }
+source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo "Error: unable to load bashlib64" && exit 1; }
 # shellcheck source-path=SCRIPTDIR/..
-source "${SYSOP64_CORE_PATH_ROOT}/github/github-lib" || { echo "Error: unable to load module library" && exit 1; }
+source "${S64_CORE_PATH_ROOT}/github/github-lib" || { echo "Error: unable to load module library" && exit 1; }
 
 #
 # Globals
@@ -48,7 +48,7 @@ function show() {
   local api_prefix="repos/${owner}/${repository}"
 
   bl64_msg_show_info 'branch protection'
-  github_lib_run_gh api "${api_prefix}"
+  s64_github_lib_run_gh api "${api_prefix}"
 }
 
 function initialize() {
@@ -61,7 +61,7 @@ function initialize() {
   bl64_check_parameter 'command' ||
     { help && return 1; }
 
-  github_lib_setup &&
+  s64_github_lib_setup &&
     bl64_check_parameter 'owner' &&
     bl64_check_parameter 'repository'
 }
@@ -105,7 +105,7 @@ while getopts ':so:r:V:D:h' option; do
   *) help && exit 1 ;;
   esac
 done
-bl64_dbg_set_level "$SYSOP64_CORE_SET_DEBUG" && bl64_msg_set_level "$SYSOP64_CORE_SET_VERBOSE" || exit $?
+bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" || exit $?
 initialize "$command" "$owner" "$repository" || exit $?
 
 bl64_msg_show_batch_start "$command"
diff --git a/src/k8s/k8s-pod-run b/src/k8s/k8s-pod-run
--- a/src/k8s/k8s-pod-run
+++ b/src/k8s/k8s-pod-run
@@ -25,16 +25,16 @@
 # Imports
 #
 
-declare SYSOP64_CORE_PATH_ROOT="${SYSOP64_CORE_PATH_ROOT:-/opt/sysop64}"
+declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
 # shellcheck source-path=SCRIPTDIR/..
-source "${SYSOP64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
+source "${S64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
 # shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
-source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
-  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-k8s.bash" &&
-  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-core.bash" ||
+source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-k8s.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" ||
   { echo "Error: unable to load bashlib64" && exit 1; }
 # shellcheck source-path=SCRIPTDIR/..
-source "${SYSOP64_CORE_PATH_ROOT}/k8s/k8s-lib" || { echo "Error: unable to load module library" && exit 1; }
+source "${S64_CORE_PATH_ROOT}/k8s/k8s-lib" || { echo "Error: unable to load module library" && exit 1; }
 
 #
 # Functions
@@ -114,7 +114,7 @@ while getopts ':si:n:e:V:D:h' option; do
   *) help && exit 1 ;;
   esac
 done
-bl64_dbg_set_level "$SYSOP64_CORE_SET_DEBUG" && bl64_msg_set_level "$SYSOP64_CORE_SET_VERBOSE" || exit $?
+bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" || exit $?
 initialize "$command" || exit $?
 
 bl64_msg_show_batch_start "$command"
diff --git a/src/linux-dev/linux-dev-crypt-mount b/src/linux-dev/linux-dev-crypt-mount
--- a/src/linux-dev/linux-dev-crypt-mount
+++ b/src/linux-dev/linux-dev-crypt-mount
@@ -25,14 +25,14 @@
 # Imports
 #
 
-declare SYSOP64_CORE_PATH_ROOT="${SYSOP64_CORE_PATH_ROOT:-/opt/sysop64}"
+declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
 # shellcheck source-path=SCRIPTDIR/..
-source "${SYSOP64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
+source "${S64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
 # shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
-source "${SYSOP64_CORE_PATH_BL64}/bashlib64-core.bash" ||
+source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" ||
   { echo "Error: unable to load bashlib64" && exit 1; }
 # shellcheck source-path=SCRIPTDIR/..
-source "${SYSOP64_CORE_PATH_ROOT}/linux/linux-lib" || { echo "Error: unable to load module library" && exit 1; }
+source "${S64_CORE_PATH_ROOT}/linux/linux-lib" || { echo "Error: unable to load module library" && exit 1; }
 
 #
 # Functions
@@ -43,7 +43,7 @@ function luks_open() {
   local device_path="${1:-}"
   local volume_name="${2:-}"
   bl64_msg_show_task "open luks device (${device_path} -> ${volume_name})"
-  linux_lib_run_cryptsetup \
+  s64_linux_lib_run_cryptsetup \
     luksOpen \
     "$device_path" \
     "$volume_name"
@@ -53,7 +53,7 @@ function fs_check() {
   bl64_dbg_app_show_function "$@"
   local volume_name="${1:-}"
   bl64_msg_show_task "check filesystem (${volume_name})"
-  linux_lib_run_fsck \
+  s64_linux_lib_run_fsck \
     "/dev/mapper/${volume_name}"
 }
 
@@ -62,7 +62,7 @@ function fs_mount() {
   local mount_point="${1:-}"
   local volume_name="${2:-}"
   bl64_msg_show_task "mount filesystem (${volume_name} -> ${mount_point})"
-  linux_lib_run_mount \
+  s64_linux_lib_run_mount \
     "/dev/mapper/${volume_name}" \
     "$mount_point"
 }
@@ -73,7 +73,7 @@ function initialize() {
     bl64_check_parameter 'device_path' &&
     bl64_check_parameter 'mount_point' &&
     bl64_check_parameter 'volume_name' &&
-    linux_lib_setup
+    s64_linux_lib_setup
 }
 
 #
@@ -85,7 +85,7 @@ declare device_path="${1:-}"
 declare mount_point="${2:-}"
 declare volume_name="${3:-}"
 
-bl64_dbg_set_level "$SYSOP64_CORE_SET_DEBUG" && bl64_msg_set_level "$SYSOP64_CORE_SET_VERBOSE" || exit $?
+bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" || exit $?
 initialize || exit $?
 
 bl64_msg_show_batch_start "$command"
diff --git a/src/linux-distro/linux-distro-upgrade b/src/linux-distro/linux-distro-upgrade
--- a/src/linux-distro/linux-distro-upgrade
+++ b/src/linux-distro/linux-distro-upgrade
@@ -26,32 +26,32 @@
 # Imports
 #
 
-declare SYSOP64_CORE_PATH_ROOT="${SYSOP64_CORE_PATH_ROOT:-/opt/sysop64}"
+declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
 # shellcheck source-path=SCRIPTDIR/..
-source "${SYSOP64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
+source "${S64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
 # shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
-source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-ui.bash" &&
-  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-xsv.bash" &&
-  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" &&
-  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-cryp.bash" &&
-  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-api.bash" &&
-  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-vcs.bash" &&
-  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-rxtx.bash" &&
-  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
-  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
-  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-fs.bash" &&
-  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-pkg.bash" &&
-  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-core.bash" ||
+source "${S64_CORE_PATH_BL64}/bashlib64-module-ui.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-xsv.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-cryp.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-api.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-vcs.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-rxtx.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-fs.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-pkg.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" ||
   { echo "Error: unable to load bashlib64" && exit 1; }
 # shellcheck source-path=SCRIPTDIR/..
-source "${SYSOP64_CORE_PATH_ROOT}/linux/linux-lib" || { echo "Error: unable to load module library" && exit 1; }
+source "${S64_CORE_PATH_ROOT}/linux/linux-lib" || { echo "Error: unable to load module library" && exit 1; }
 
 #
 # Globals
 #
 
 # Distro dependant upgrade command
-declare _SYSOP64_LINUX_DISTRO_DO_RELEASE_UPGRADE=''
+declare _S64_LINUX_DISTRO_DO_RELEASE_UPGRADE=''
 
 #
 # Functions
@@ -98,7 +98,7 @@ function prepare_ubuntu() {
 
 function upgrade_ubuntu() {
   bl64_dbg_app_show_function
-  "$_SYSOP64_LINUX_DISTRO_DO_RELEASE_UPGRADE" \
+  "$_S64_LINUX_DISTRO_DO_RELEASE_UPGRADE" \
     --allow-third-party \
     --frontend=DistUpgradeViewNonInteractive
 }
@@ -143,8 +143,8 @@ function initialize() {
   if [[ "$command" == 'upgrade' ]]; then
     case "$BL64_OS_DISTRO" in
     ${BL64_OS_UB}-*)
-      _SYSOP64_LINUX_DISTRO_DO_RELEASE_UPGRADE='/bin/do-release-upgrade'
-      bl64_check_command "$_SYSOP64_LINUX_DISTRO_DO_RELEASE_UPGRADE"
+      _S64_LINUX_DISTRO_DO_RELEASE_UPGRADE='/bin/do-release-upgrade'
+      bl64_check_command "$_S64_LINUX_DISTRO_DO_RELEASE_UPGRADE"
       ;;
     *) : ;;
     esac
@@ -189,7 +189,7 @@ while getopts ':pur:V:D:h' option; do
   *) help && exit 1 ;;
   esac
 done
-bl64_dbg_set_level "$SYSOP64_CORE_SET_DEBUG" && bl64_msg_set_level "$SYSOP64_CORE_SET_VERBOSE" || exit $?
+bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" || exit $?
 initialize "$command" || exit $?
 
 bl64_msg_show_batch_start "$command"
diff --git a/src/pgsql/pgsql-index-info b/src/pgsql/pgsql-index-info
--- a/src/pgsql/pgsql-index-info
+++ b/src/pgsql/pgsql-index-info
@@ -25,13 +25,13 @@
 # Imports
 #
 
-declare SYSOP64_CORE_PATH_ROOT="${SYSOP64_CORE_PATH_ROOT:-/opt/sysop64}"
+declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
 # shellcheck source-path=SCRIPTDIR/..
-source "${SYSOP64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
+source "${S64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
 # shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
-source "${SYSOP64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo "Error: unable to load bashlib64" && exit 1; }
+source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo "Error: unable to load bashlib64" && exit 1; }
 # shellcheck source-path=SCRIPTDIR/..
-source "${SYSOP64_CORE_PATH_ROOT}/pgsql/pgsql-lib" || { echo "Error: unable to load module library" && exit 1; }
+source "${S64_CORE_PATH_ROOT}/pgsql/pgsql-lib" || { echo "Error: unable to load module library" && exit 1; }
 
 #
 # Globals
@@ -47,22 +47,22 @@ export PSQL_PAGER=''
 function list() {
   bl64_dbg_app_show_function "$@"
   local index="$1"
-  psql_lib_run_psql \
-    --host="$SYSOP64_PGSQL_SERVER_HOST" \
-    --port="$SYSOP64_PGSQL_SERVER_PORT" \
-    --dbname="$SYSOP64_PGSQL_DB_NAME" \
-    --username="$SYSOP64_PGSQL_SERVER_USER" \
+  s64_psql_lib_run_psql \
+    --host="$S64_PGSQL_SERVER_HOST" \
+    --port="$S64_PGSQL_SERVER_PORT" \
+    --dbname="$S64_PGSQL_DB_NAME" \
+    --username="$S64_PGSQL_SERVER_USER" \
     --command="\\di"
 }
 
 function describe() {
   bl64_dbg_app_show_function "$@"
   local index="$1"
-  psql_lib_run_psql \
-    --host="$SYSOP64_PGSQL_SERVER_HOST" \
-    --port="$SYSOP64_PGSQL_SERVER_PORT" \
-    --dbname="$SYSOP64_PGSQL_DB_NAME" \
-    --username="$SYSOP64_PGSQL_SERVER_USER" \
+  s64_psql_lib_run_psql \
+    --host="$S64_PGSQL_SERVER_HOST" \
+    --port="$S64_PGSQL_SERVER_PORT" \
+    --dbname="$S64_PGSQL_DB_NAME" \
+    --username="$S64_PGSQL_SERVER_USER" \
     --command="\\d $index"
 }
 
@@ -75,11 +75,11 @@ SELECT
 FROM
   pg_stat_progress_create_index
 ;' |
-    psql_lib_run_psql \
-      --host="$SYSOP64_PGSQL_SERVER_HOST" \
-      --port="$SYSOP64_PGSQL_SERVER_PORT" \
-      --dbname="$SYSOP64_PGSQL_DB_NAME" \
-      --username="$SYSOP64_PGSQL_SERVER_USER" \
+    s64_psql_lib_run_psql \
+      --host="$S64_PGSQL_SERVER_HOST" \
+      --port="$S64_PGSQL_SERVER_PORT" \
+      --dbname="$S64_PGSQL_DB_NAME" \
+      --username="$S64_PGSQL_SERVER_USER" \
       --file='-'
 }
 
@@ -92,8 +92,8 @@ function initialize() {
   bl64_check_parameter 'command' ||
     { help && return 1; }
 
-  psql_lib_setup &&
-    bl64_check_export 'SYSOP64_PGSQL_SERVER_PASSWORD' ||
+  s64_psql_lib_setup &&
+    bl64_check_export 'S64_PGSQL_SERVER_PASSWORD' ||
     return $?
 
   if [[ "$command" == 'describe' ]]; then
@@ -101,7 +101,7 @@ function initialize() {
       return $?
   fi
 
-  PGPASSWORD="$SYSOP64_PGSQL_SERVER_PASSWORD"
+  PGPASSWORD="$S64_PGSQL_SERVER_PASSWORD"
 }
 
 function help() {
@@ -113,10 +113,10 @@ function help() {
     -e         : Describe index
     -k         : Check index status
     ' '
-    -o Host    : Host FQDN. Alternative shell-env: SYSOP64_PGSQL_SERVER_HOST  
-    -p Port    : DB Port. Alternative shell-ehv: SYSOP64_PGSQL_SERVER_PORT 
-    -u User    : DB User. Alternative shell-ehv: SYSOP64_PGSQL_SERVER_USER 
-    -b DB      : DB Name. Alternative shell-ehv: SYSOP64_PGSQL_DB_NAME
+    -o Host    : Host FQDN. Alternative shell-env: S64_PGSQL_SERVER_HOST  
+    -p Port    : DB Port. Alternative shell-ehv: S64_PGSQL_SERVER_PORT 
+    -u User    : DB User. Alternative shell-ehv: S64_PGSQL_SERVER_USER 
+    -b DB      : DB Name. Alternative shell-ehv: S64_PGSQL_DB_NAME
     -x Index   : DB Table.
     -h         : Show help
     ' '
@@ -141,10 +141,10 @@ while getopts ':leko:p:u:b:x:V:D:h' option; do
   l) command='list' ;;
   e) command='describe' ;;
   k) command='check' ;;
-  o) SYSOP64_PGSQL_SERVER_HOST="$OPTARG" ;;
-  p) SYSOP64_PGSQL_SERVER_PORT="$OPTARG" ;;
-  u) SYSOP64_PGSQL_SERVER_USER="$OPTARG" ;;
-  b) SYSOP64_PGSQL_DB_NAME="$OPTARG" ;;
+  o) S64_PGSQL_SERVER_HOST="$OPTARG" ;;
+  p) S64_PGSQL_SERVER_PORT="$OPTARG" ;;
+  u) S64_PGSQL_SERVER_USER="$OPTARG" ;;
+  b) S64_PGSQL_DB_NAME="$OPTARG" ;;
   x) index="$OPTARG" ;;
   V) verbose="$OPTARG" ;;
   D) debug="$OPTARG" ;;
@@ -152,7 +152,7 @@ while getopts ':leko:p:u:b:x:V:D:h' option; do
   *) help && exit 1 ;;
   esac
 done
-bl64_dbg_set_level "$SYSOP64_CORE_SET_DEBUG" && bl64_msg_set_level "$SYSOP64_CORE_SET_VERBOSE" || exit $?
+bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" || exit $?
 initialize "$command" "$index" || exit $?
 
 bl64_msg_show_batch_start "$command"
diff --git a/src/pgsql/pgsql-server-lab-control b/src/pgsql/pgsql-server-lab-control
--- a/src/pgsql/pgsql-server-lab-control
+++ b/src/pgsql/pgsql-server-lab-control
@@ -25,19 +25,19 @@
 # Imports
 #
 
-declare SYSOP64_CORE_PATH_ROOT="${SYSOP64_CORE_PATH_ROOT:-/opt/sysop64}"
+declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
 # shellcheck source-path=SCRIPTDIR/..
-source "${SYSOP64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
+source "${S64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
 # shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
-source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-fs.bash" &&
-  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
-  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-xsv.bash" &&
-  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
-  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" &&
-  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-cnt.bash" &&
-  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo "Error: unable to load bashlib64" && exit 1; }
+source "${S64_CORE_PATH_BL64}/bashlib64-module-fs.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-xsv.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-cnt.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo "Error: unable to load bashlib64" && exit 1; }
 # shellcheck source-path=SCRIPTDIR/..
-source "${SYSOP64_CORE_PATH_ROOT}/pgsql/pgsql-lib" || { echo "Error: unable to load module library" && exit 1; }
+source "${S64_CORE_PATH_ROOT}/pgsql/pgsql-lib" || { echo "Error: unable to load module library" && exit 1; }
 
 #
 # Functions
@@ -48,14 +48,14 @@ function start() {
   local container_port='5432'
   bl64_msg_show_task 'start Postgresql Server in container mode'
   bl64_cnt_run \
-    --name "$SYSOP64_PGSQL_SERVER_LAB_NAME" \
-    --env POSTGRES_PASSWORD="$SYSOP64_PGSQL_SERVER_LAB_PASSWORD" \
+    --name "$S64_PGSQL_SERVER_LAB_NAME" \
+    --env POSTGRES_PASSWORD="$S64_PGSQL_SERVER_LAB_PASSWORD" \
     --detach \
     --publish "$container_port:$container_port" \
     postgres &&
     bl64_msg_show_info "Starded container information
-Container Name: ${SYSOP64_PGSQL_SERVER_LAB_NAME}
-Password: ${SYSOP64_PGSQL_SERVER_LAB_PASSWORD}
+Container Name: ${S64_PGSQL_SERVER_LAB_NAME}
+Password: ${S64_PGSQL_SERVER_LAB_PASSWORD}
 Port: ${container_port}"
 }
 
@@ -64,10 +64,10 @@ function stop() {
   bl64_msg_show_task 'stop Postgresql Server running in container mode'
   bl64_cnt_cli \
     stop \
-    "$SYSOP64_PGSQL_SERVER_LAB_NAME" &&
+    "$S64_PGSQL_SERVER_LAB_NAME" &&
     bl64_cnt_cli \
       rm \
-      "$SYSOP64_PGSQL_SERVER_LAB_NAME"
+      "$S64_PGSQL_SERVER_LAB_NAME"
 }
 
 function initialize() {
@@ -117,7 +117,7 @@ while getopts ':soV:D:h' option; do
   *) help && exit 1 ;;
   esac
 done
-bl64_dbg_set_level "$SYSOP64_CORE_SET_DEBUG" && bl64_msg_set_level "$SYSOP64_CORE_SET_VERBOSE" || exit $?
+bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" || exit $?
 initialize "$command" || exit $?
 
 bl64_msg_show_batch_start "$command"
diff --git a/src/pgsql/pgsql-table-info b/src/pgsql/pgsql-table-info
--- a/src/pgsql/pgsql-table-info
+++ b/src/pgsql/pgsql-table-info
@@ -25,13 +25,13 @@
 # Imports
 #
 
-declare SYSOP64_CORE_PATH_ROOT="${SYSOP64_CORE_PATH_ROOT:-/opt/sysop64}"
+declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
 # shellcheck source-path=SCRIPTDIR/..
-source "${SYSOP64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
+source "${S64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
 # shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
-source "${SYSOP64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo "Error: unable to load bashlib64" && exit 1; }
+source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo "Error: unable to load bashlib64" && exit 1; }
 # shellcheck source-path=SCRIPTDIR/..
-source "${SYSOP64_CORE_PATH_ROOT}/pgsql/pgsql-lib" || { echo "Error: unable to load module library" && exit 1; }
+source "${S64_CORE_PATH_ROOT}/pgsql/pgsql-lib" || { echo "Error: unable to load module library" && exit 1; }
 
 #
 # Globals
@@ -47,22 +47,22 @@ export PSQL_PAGER=''
 function list() {
   bl64_dbg_app_show_function "$@"
   local table="$1"
-  psql_lib_run_psql \
-    --host="$SYSOP64_PGSQL_SERVER_HOST" \
-    --port="$SYSOP64_PGSQL_SERVER_PORT" \
-    --dbname="$SYSOP64_PGSQL_DB_NAME" \
-    --username="$SYSOP64_PGSQL_SERVER_USER" \
+  s64_psql_lib_run_psql \
+    --host="$S64_PGSQL_SERVER_HOST" \
+    --port="$S64_PGSQL_SERVER_PORT" \
+    --dbname="$S64_PGSQL_DB_NAME" \
+    --username="$S64_PGSQL_SERVER_USER" \
     --command="\\dt"
 }
 
 function describe() {
   bl64_dbg_app_show_function "$@"
   local table="$1"
-  psql_lib_run_psql \
-    --host="$SYSOP64_PGSQL_SERVER_HOST" \
-    --port="$SYSOP64_PGSQL_SERVER_PORT" \
-    --dbname="$SYSOP64_PGSQL_DB_NAME" \
-    --username="$SYSOP64_PGSQL_SERVER_USER" \
+  s64_psql_lib_run_psql \
+    --host="$S64_PGSQL_SERVER_HOST" \
+    --port="$S64_PGSQL_SERVER_PORT" \
+    --dbname="$S64_PGSQL_DB_NAME" \
+    --username="$S64_PGSQL_SERVER_USER" \
     --command="\\d $table"
 }
 
@@ -75,8 +75,8 @@ function initialize() {
   bl64_check_parameter 'command' ||
     { help && return 1; }
 
-  psql_lib_setup &&
-    bl64_check_export 'SYSOP64_PGSQL_SERVER_PASSWORD' ||
+  s64_psql_lib_setup &&
+    bl64_check_export 'S64_PGSQL_SERVER_PASSWORD' ||
     return $?
 
   if [[ "$command" == 'describe' ]]; then
@@ -84,7 +84,7 @@ function initialize() {
       return $?
   fi
 
-  PGPASSWORD="$SYSOP64_PGSQL_SERVER_PASSWORD"
+  PGPASSWORD="$S64_PGSQL_SERVER_PASSWORD"
 }
 
 function help() {
@@ -95,10 +95,10 @@ function help() {
     -l         : List tables
     -e         : Describe table
     ' '
-    -o Host    : Host FQDN. Alternative shell-env: SYSOP64_PGSQL_SERVER_HOST  
-    -p Port    : DB Port. Alternative shell-ehv: SYSOP64_PGSQL_SERVER_PORT 
-    -u User    : DB User. Alternative shell-ehv: SYSOP64_PGSQL_SERVER_USER 
-    -b DB      : DB Name. Alternative shell-ehv: SYSOP64_PGSQL_DB_NAME
+    -o Host    : Host FQDN. Alternative shell-env: S64_PGSQL_SERVER_HOST  
+    -p Port    : DB Port. Alternative shell-ehv: S64_PGSQL_SERVER_PORT 
+    -u User    : DB User. Alternative shell-ehv: S64_PGSQL_SERVER_USER 
+    -b DB      : DB Name. Alternative shell-ehv: S64_PGSQL_DB_NAME
     -t Table   : DB Table.
     -h         : Show help
     ' '
@@ -122,10 +122,10 @@ while getopts ':leo:p:u:b:t:V:D:h' option; do
   case "$option" in
   l) command='list' ;;
   e) command='describe' ;;
-  o) SYSOP64_PGSQL_SERVER_HOST="$OPTARG" ;;
-  p) SYSOP64_PGSQL_SERVER_PORT="$OPTARG" ;;
-  u) SYSOP64_PGSQL_SERVER_USER="$OPTARG" ;;
-  b) SYSOP64_PGSQL_DB_NAME="$OPTARG" ;;
+  o) S64_PGSQL_SERVER_HOST="$OPTARG" ;;
+  p) S64_PGSQL_SERVER_PORT="$OPTARG" ;;
+  u) S64_PGSQL_SERVER_USER="$OPTARG" ;;
+  b) S64_PGSQL_DB_NAME="$OPTARG" ;;
   t) table="$OPTARG" ;;
   V) verbose="$OPTARG" ;;
   D) debug="$OPTARG" ;;
@@ -133,7 +133,7 @@ while getopts ':leo:p:u:b:t:V:D:h' option; do
   *) help && exit 1 ;;
   esac
 done
-bl64_dbg_set_level "$SYSOP64_CORE_SET_DEBUG" && bl64_msg_set_level "$SYSOP64_CORE_SET_VERBOSE" || exit $?
+bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" || exit $?
 initialize "$command" "$table" || exit $?
 
 bl64_msg_show_batch_start "$command"
