refact: normalize

diff --git a/src/pgsql/pgsql-server-lab-control b/src/pgsql/pgsql-server-lab-control
--- a/src/pgsql/pgsql-server-lab-control
+++ b/src/pgsql/pgsql-server-lab-control
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
-# template: 1.0.0
+# template-task: 2.0.0
 #######################################
 # PGSQL / Server / Lab / Control
 #
-# Version: 1.0.1
+# Version: 1.0.2
 #
 #######################################
 # Copyright [2024] [serdigital64@gmail.com]
@@ -27,17 +27,9 @@
 
 declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
 # shellcheck source-path=SCRIPTDIR/..
-source "${S64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
+source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/pgsql-lib" || { echo "Error: unable to load module library" && exit 1; }
 # shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
-source "${S64_CORE_PATH_BL64}/bashlib64-module-fs.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-module-xsv.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-module-cnt.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }
-# shellcheck source-path=SCRIPTDIR/..
-source "${S64_CORE_PATH_ROOT}/pgsql/pgsql-lib" || { echo "Error: unable to load module library" && exit 1; }
+source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }
 
 #
 # Functions
@@ -71,11 +63,9 @@ function stop() {
 }
 
 function initialize() {
-  bl64_dbg_app_show_function "$@"
-  # shellcheck disable=SC2034
-  local command="$1"
+  bl64_dbg_app_show_function
 
-  bl64_check_parameter 'command' ||
+  bl64_check_parameter 'COMMAND' ||
     { help && return 1; }
 
   bl64_cnt_check_not_in_container &&
@@ -101,25 +91,22 @@ function help() {
 # Main
 #
 
-declare command="$BL64_VAR_NULL"
-declare debug="$BL64_DBG_TARGET_NONE"
-declare option=''
-declare verbose="$BL64_MSG_VERBOSE_ALL"
+declare COMMAND="$BL64_VAR_NULL"
+declare OPTION=''
 
 (($# == 0)) && help && exit 1
-while getopts ':soV:D:h' option; do
-  case "$option" in
-  s) command='start' ;;
-  o) command='stop' ;;
-  V) verbose="$OPTARG" ;;
-  D) debug="$OPTARG" ;;
+while getopts ':soV:D:h' OPTION; do
+  case "$OPTION" in
+  s) COMMAND='start' ;;
+  o) COMMAND='stop' ;;
+  V) S64_CORE_SET_VERBOSE="$OPTARG" ;;
+  D) S64_CORE_SET_DEBUG="$OPTARG" ;;
   h) help && exit 0 ;;
   *) help && exit 1 ;;
   esac
 done
-bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" || exit $?
-initialize "$command" || exit $?
+bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && initialize || exit $?
 
-bl64_msg_show_batch_start "$command"
-"${command}"
-bl64_msg_show_batch_finish $? "$command"
+bl64_msg_show_batch_start "${BL64_SCRIPT_ID}:$COMMAND"
+"${COMMAND}"
+bl64_msg_show_batch_finish $? "${BL64_SCRIPT_ID}:$COMMAND"
