feat: add user context, upgrade skeletons (#17)

diff --git a/docs/skeletons/module-lib/module-lib b/docs/skeletons/module-lib/module-lib
--- a/docs/skeletons/module-lib/module-lib
+++ b/docs/skeletons/module-lib/module-lib
@@ -1,8 +1,9 @@
 #!/usr/bin/env bash
-# template: 1.1.0
-# template-module-setup: 1.1.0
-# template-module-cli: 1.1.0
-# template-module-vars: 1.0.0
+# template-module-lib: 2.0.0
+#   template-module-base: 2.0.0
+#   template-module-setup: 2.0.0
+#   template-module-cli: 1.1.0
+#   template-module-vars: 1.0.0
 #######################################
 # X_MODULE_NAME_X / Lib
 #
@@ -25,6 +26,14 @@
 #######################################
 
 #
+# Imports
+#
+
+# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" ||
+  { echo "Error: unable to load bashlib64" && exit 1; }
+
+#
 # Globals
 #
 
@@ -39,23 +48,10 @@
 
 function s64_X_MODULE_X_lib_setup() {
   bl64_dbg_app_show_function
-  local command='X_MODULE_COMMAND_CLI_X'
   if [[ -z "$S64_X_MODULE_CAPS_X_PATH_CLI" ]]; then
-    if [[ -x "/home/linuxbrew/.linuxbrew/bin/${command}" ]]; then
-      S64_X_MODULE_CAPS_X_PATH_CLI="/home/linuxbrew/.linuxbrew/bin/${command}"
-    elif [[ -x "/opt/homebrew/bin/${command}" ]]; then
-      S64_X_MODULE_CAPS_X_PATH_CLI="/opt/homebrew/bin/${command}"
-    elif [[ -x "/usr/local/bin/${command}" ]]; then
-      S64_X_MODULE_CAPS_X_PATH_CLI="/usr/local/bin/${command}"
-    elif [[ -x "/usr/bin/${command}" ]]; then
-      S64_X_MODULE_CAPS_X_PATH_CLI="/usr/bin/${command}"
-    else
-      bl64_check_alert_resource_not_found "$command"
-      return $?
-    fi
+    S64_X_MODULE_CAPS_X_PATH_CLI="$(bl64_bsh_command_locate 'argocd')"
   else
-    bl64_check_command "$S64_X_MODULE_CAPS_X_PATH_CLI" ||
-      return $?
+    bl64_check_command "$S64_X_MODULE_CAPS_X_PATH_CLI"
   fi
 }
 
diff --git a/docs/skeletons/task-generic/module-task b/docs/skeletons/task-generic/module-task
--- a/docs/skeletons/task-generic/module-task
+++ b/docs/skeletons/task-generic/module-task
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
-# template: 1.0.0
-# template-import: 1.0.0
+# template-task: 2.0.0
+#   template-task-base: 1.1.0
+#   template-import: 2.0.0
 #######################################
 # X_MODULE_NAME_X / [X_SUBMODULE_NAME_X /] X_APP_NAME_X
 #
@@ -29,11 +30,11 @@
 declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
 # shellcheck source-path=SCRIPTDIR/..
 source "${S64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
+# shellcheck source-path=SCRIPTDIR/..
+source "${S64_CORE_PATH_ROOT}/X_MODULE_X/X_MODULE_X-lib" || { echo "Error: unable to load module library" && exit 1; }
 # shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
 source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" ||
   { echo "Error: unable to load bashlib64" && exit 1; }
-# shellcheck source-path=SCRIPTDIR/..
-source "${S64_CORE_PATH_ROOT}/X_MODULE_X/X_MODULE_X-lib" || { echo "Error: unable to load module library" && exit 1; }
 
 #
 # Globals
@@ -51,9 +52,7 @@ function X_COMMAND_X() {
 }
 
 function initialize() {
-  bl64_dbg_app_show_function "$@"
-  # shellcheck disable=SC2034
-  local command="$1"
+  bl64_dbg_app_show_function
 
   bl64_check_parameter 'command' ||
     { help && return 1; }
@@ -82,23 +81,21 @@ function help() {
 #
 
 declare command="$BL64_VAR_NULL"
-declare debug="$BL64_DBG_TARGET_NONE"
 declare option=''
-declare verbose="$BL64_MSG_VERBOSE_ALL"
 
 (($# == 0)) && help && exit 1
 while getopts ':xV:D:h' option; do
   case "$option" in
   x) command='X_COMMAND_X' ;;
-  V) verbose="$OPTARG" ;;
-  D) debug="$OPTARG" ;;
+  V) S64_CORE_SET_VERBOSE="$OPTARG" ;;
+  D) S64_CORE_SET_DEBUG="$OPTARG" ;;
   h) help && exit 0 ;;
   *) help && exit 1 ;;
   esac
 done
 bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" || exit $?
-initialize "$command" || exit $?
+initialize || exit $?
 
-bl64_msg_show_batch_start "$command"
+bl64_msg_show_batch_start "${BL64_SCRIPT_ID}:$command"
 "${command}"
-bl64_msg_show_batch_finish $? "$command"
+bl64_msg_show_batch_finish $? "${BL64_SCRIPT_ID}:$command"
diff --git a/src/k8s/k8s-pod-run b/src/k8s/k8s-pod-run
--- a/src/k8s/k8s-pod-run
+++ b/src/k8s/k8s-pod-run
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
-# template: 1.0.0
+# template-task: 2.0.0
 #######################################
 # K8S / Pod / Run
 #
-# Version: 1.0.2
+# Version: 2.0.0
 #
 #######################################
 # Copyright [2024] [serdigital64@gmail.com]
@@ -28,13 +28,11 @@
 declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
 # shellcheck source-path=SCRIPTDIR/..
 source "${S64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
-# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
-source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-module-k8s.bash" &&
-  source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" ||
-  { echo "Error: unable to load bashlib64" && exit 1; }
 # shellcheck source-path=SCRIPTDIR/..
 source "${S64_CORE_PATH_ROOT}/k8s/k8s-lib" || { echo "Error: unable to load module library" && exit 1; }
+# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" ||
+  { echo "Error: unable to load bashlib64" && exit 1; }
 
 #
 # Functions
@@ -63,14 +61,8 @@ function shell_run() {
 }
 
 function initialize() {
-  bl64_dbg_app_show_function "$@"
-  # shellcheck disable=SC2034
-  local command="$1"
-
-  bl64_check_parameter 'command' ||
-    { help && return 1; }
-
-  bl64_k8s_setup
+  bl64_dbg_app_show_function
+  s64_k8s_lib_setup
 }
 
 function help() {
@@ -95,9 +87,7 @@ function help() {
 #
 
 declare command='shell_run'
-declare debug="$BL64_DBG_TARGET_NONE"
 declare option=''
-declare verbose="$BL64_MSG_VERBOSE_ALL"
 declare namespace='default'
 declare image="$BL64_VAR_DEFAULT"
 declare entrypoint="$BL64_VAR_DEFAULT"
@@ -108,15 +98,15 @@ while getopts ':si:n:e:V:D:h' option; do
   n) namespace="$OPTARG" ;;
   i) image="$OPTARG" ;;
   e) entrypoint="$OPTARG" ;;
-  V) verbose="$OPTARG" ;;
-  D) debug="$OPTARG" ;;
+  V) S64_CORE_SET_VERBOSE="$OPTARG" ;;
+  D) S64_CORE_SET_DEBUG="$OPTARG" ;;
   h) help && exit 0 ;;
   *) help && exit 1 ;;
   esac
 done
 bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" || exit $?
-initialize "$command" || exit $?
+initialize || exit $?
 
-bl64_msg_show_batch_start "$command"
+bl64_msg_show_batch_start "${BL64_SCRIPT_ID}:$command"
 "${command}" "$namespace" "$image" "$entrypoint"
-bl64_msg_show_batch_finish $? "$command"
+bl64_msg_show_batch_finish $? "${BL64_SCRIPT_ID}:$command"
