feat: add argocd cmds

diff --git a/src/argocd/argocd-lib b/src/argocd/argocd-lib
--- a/src/argocd/argocd-lib
+++ b/src/argocd/argocd-lib
@@ -3,7 +3,7 @@
 #######################################
 # ArgoCD / Lib
 #
-# Version: 1.0.0
+# Version: 1.1.0
 #
 #######################################
 # Copyright [2024] [serdigital64@gmail.com]
@@ -22,43 +22,57 @@
 #######################################
 
 #
+# Imports
+#
+
+# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-xsv.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-fs.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-k8s.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" ||
+  { echo "Error: unable to load bashlib64" && exit 1; }
+
+#
 # Globals
 #
 
 # shellcheck disable=SC2034
 {
   declare S64_ARGOCD_PATH_CLI="${S64_ARGOCD_PATH_CLI:-}"
+  # Global Settings
+  declare S64_ARGOCD_SET_CONNECTION='--core'
+  declare S64_ARGOCD_SET_CONTEXT_CLUSTER="${S64_ARGOCD_SET_CONTEXT_CLUSTER:-}"
+  declare S64_ARGOCD_SET_CONTEXT_NAMESPACE="${S64_ARGOCD_SET_CONTEXT_NAMESPACE:-argocd}"
+  declare S64_ARGOCD_SET_CONTEXT_NAME="${S64_ARGOCD_SET_CONTEXT_NAME:-argocdcli}"
 }
 
 #
 # Functions
 #
 
-function s64_X_MODULE_X_lib_setup() {
+function s64_argocd_lib_setup() {
   bl64_dbg_app_show_function
+
+  bl64_k8s_setup &&
+    bl64_check_export 'S64_ARGOCD_SET_CONTEXT_CLUSTER' ||
+    return $?
+
   if [[ -z "$S64_ARGOCD_PATH_CLI" ]]; then
-    if [[ -x '/home/linuxbrew/.linuxbrew/bin/argocd' ]]; then
-      S64_ARGOCD_PATH_CLI='/home/linuxbrew/.linuxbrew/bin/argocd'
-    elif [[ -x '/opt/homebrew/bin/argocd' ]]; then
-      S64_ARGOCD_PATH_CLI='/opt/homebrew/bin/argocd'
-    elif [[ -x '/usr/local/bin/argocd' ]]; then
-      S64_ARGOCD_PATH_CLI='/usr/local/bin/argocd'
-    elif [[ -x '/usr/bin/argocd' ]]; then
-      S64_ARGOCD_PATH_CLI='/usr/bin/argocd'
-    else
-      bl64_check_alert_resource_not_found 'argocd'
-      return $?
-    fi
+    S64_ARGOCD_PATH_CLI="$(bl64_bsh_command_locate 'argocd')"
   else
-    bl64_check_command "$S64_ARGOCD_PATH_CLI" ||
-      return $?
+    bl64_check_command "$S64_ARGOCD_PATH_CLI"
   fi
 }
 
 function s64_argocd_lib_run_argocd() {
   bl64_dbg_app_show_function "$@"
   bl64_dbg_app_trace_start
+  # shellcheck disable=SC2086
   "$S64_ARGOCD_PATH_CLI" \
+    --kube-context="$S64_ARGOCD_SET_CONTEXT_NAME" \
+    $S64_ARGOCD_SET_CONNECTION \
     "$@"
   bl64_dbg_app_trace_stop
 }
