refact: normalize

diff --git a/src/github-repo/github-repo-show b/src/github-repo/github-repo-show
--- a/src/github-repo/github-repo-show
+++ b/src/github-repo/github-repo-show
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# template: 1.0.0
+# template-task: 2.0.0
 #######################################
 # GitHub / Repo / Show
 #
@@ -27,15 +27,9 @@
 
 declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
 # shellcheck source-path=SCRIPTDIR/..
-source "${S64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
+source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/github-lib" || { echo "Error: unable to load module library" && exit 1; }
 # shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
 source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }
-# shellcheck source-path=SCRIPTDIR/..
-source "${S64_CORE_PATH_ROOT}/github/github-lib" || { echo "Error: unable to load module library" && exit 1; }
-
-#
-# Globals
-#
 
 #
 # Functions
@@ -52,18 +46,13 @@ function show() {
 }
 
 function initialize() {
-  bl64_dbg_app_show_function "$@"
-  # shellcheck disable=SC2034
-  local command="$1"
-  local owner="$2"
-  local repository="$3"
-
-  bl64_check_parameter 'command' ||
+  bl64_dbg_app_show_function
+  bl64_check_parameter 'COMMAND' ||
     { help && return 1; }
 
-  s64_github_lib_setup &&
-    bl64_check_parameter 'owner' &&
-    bl64_check_parameter 'repository'
+  bl64_check_parameter 'REPO_OWNER' &&
+    bl64_check_parameter 'REPO_NAME' &&
+    s64_github_lib_setup
 }
 
 function help() {
@@ -86,28 +75,24 @@ function help() {
 # Main
 #
 
-declare command="$BL64_VAR_NULL"
-declare debug="$BL64_DBG_TARGET_NONE"
-declare option=''
-declare verbose="$BL64_MSG_VERBOSE_ALL"
-declare owner=''
-declare repository=''
+declare COMMAND="$BL64_VAR_NULL"
+declare OPTION=''
+declare REPO_OWNER=''
+declare REPO_NAME=''
 
 (($# == 0)) && help && exit 1
-while getopts ':so:r:V:D:h' option; do
-  case "$option" in
-  s) command='show' ;;
-  o) owner="$OPTARG" ;;
-  r) repository="$OPTARG" ;;
-  V) verbose="$OPTARG" ;;
-  D) debug="$OPTARG" ;;
+while getopts ':so:r:V:D:h' OPTION; do
+  case "$OPTION" in
+  s) COMMAND='show' ;;
+  o) REPO_OWNER="$OPTARG" ;;
+  r) REPO_NAME="$OPTARG" ;;
+  V) S64_CORE_SET_VERBOSE="$OPTARG" ;;
+  D) S64_CORE_SET_DEBUG="$OPTARG" ;;
   h) help && exit 0 ;;
   *) help && exit 1 ;;
   esac
 done
-bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" || exit $?
-initialize "$command" "$owner" "$repository" || exit $?
-
-bl64_msg_show_batch_start "$command"
-"$command" "$owner" "$repository"
-bl64_msg_show_batch_finish $? "$command"
+bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && initialize || exit $?
+bl64_msg_show_batch_start "${BL64_SCRIPT_ID}:$COMMAND"
+"$COMMAND" "$REPO_OWNER" "$REPO_NAME"
+bl64_msg_show_batch_finish $? "${BL64_SCRIPT_ID}:$COMMAND"
