real: promote 1.13.0 (#40)

diff --git a/src/macos-package/macos-package-show-files b/src/macos-package/macos-package-show-files
--- a/src/macos-package/macos-package-show-files
+++ b/src/macos-package/macos-package-show-files
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# template-one: 3.0.0
+# template-one: 3.2.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -17,53 +17,25 @@ declare S64_CORE_PATH_AT64="${HOME}/at64"
 [[ ! -d "$S64_CORE_PATH_AT64" ]] && S64_CORE_PATH_AT64='/opt'
 declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-${S64_CORE_PATH_AT64}/sysop64}"
 # shellcheck disable=SC2015 source-path=SCRIPTDIR/..
-source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/linux-lib" ||
-  { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
-# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/macos-lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
+# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
 source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }
 
-function list() {
-  bl64_dbg_app_show_function
-  case "$BL64_OS_DISTRO" in
-  ${BL64_OS_UB}-* | ${BL64_OS_DEB}-* | ${BL64_OS_KL}-*)
-    bl64_pkg_run_apt \
-      'list' \
-      --installed
-    ;;
-  ${BL64_OS_FD}-* | ${BL64_OS_AMZ}-*)
-    bl64_pkg_run_dnf \
-      'list' \
-      --installed
-    ;;
-  ${BL64_OS_CNT}-7.* | ${BL64_OS_OL}-7.*)
-    bl64_pkg_run_yum \
-      'list' \
-      installed
-    ;;
-  ${BL64_OS_CNT}-* | ${BL64_OS_OL}-* | ${BL64_OS_RHEL}-* | ${BL64_OS_ALM}-* | ${BL64_OS_RCK}-*)
-    bl64_pkg_run_dnf \
-      'list' \
-      --installed
-    ;;
-  ${BL64_OS_ALP}-*)
-    bl64_pkg_run_apk \
-      'list' \
-      --installed
-    ;;
-    *)
-      bl64_check_alert_unsupported
-      return $?
-      ;;
-    esac
-}
+declare MY_PACKAGE_NAME=''
 
 function my_initialize() {
   bl64_dbg_app_show_function
-  bl64_check_privilege_root
+  s64_macos_lib_setup &&
+  bl64_check_parameter 'MY_PACKAGE_NAME' ||
+    return $?
+  bl64_msg_show_about
 }
 
-bl64_lib_script_version_set '1.0.1'
+bl64_lib_script_version_set '1.0.0'
+bl64_msg_help_about_set 'Show OS package content'
 bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && my_initialize || exit $?
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
-list
+s64_macos_lib_run_pkgutil \
+  --files \
+  "$MY_PACKAGE_NAME"
 bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
