feat: add linux dm, repo

diff --git a/src/linux-package/linux-repo-enable b/src/linux-package/linux-repo-enable
--- a/src/linux-package/linux-repo-enable
+++ b/src/linux-package/linux-repo-enable
@@ -16,30 +16,43 @@
 declare S64_CORE_PATH_AT64="${HOME}/at64"
 [[ ! -d "$S64_CORE_PATH_AT64" ]] && S64_CORE_PATH_AT64='/opt'
 declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-${S64_CORE_PATH_AT64}/sysop64}"
-# shellcheck disable=SC2015 source-path=SCRIPTDIR/..
-source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/linux-lib" ||
-  { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
-# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
-source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }
+# shellcheck source-path=SCRIPTDIR/..
+source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/linux-lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
+# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
+source "${S64_CORE_PATH_BL64}/bashlib64-module-pkg.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }
 
-declare MY_VOLUME_NAME="${1:-}"
+declare MY_REPOSITORY_ID="${1:-}"
+
+function my_repo_enable_dnfv5() {
+  bl64_dbg_app_show_function "$@"
+  local repo="$1"
+  bl64_pkg_run_dnf config-manager setopt "$repo.enabled=1"
+}
+
+function my_repo_enable() {
+  bl64_dbg_app_show_function "$@"
+  local repo="$1"
+  case "$BL64_OS_DISTRO" in
+  ${BL64_OS_FD}-4?.*) my_repo_enable_dnfv5 "$repo" ;;
+  *) bl64_check_alert_unsupported ;;
+  esac
+}
 
 function my_initialize() {
   bl64_dbg_app_show_function
   bl64_check_privilege_root &&
-    bl64_check_parameter 'MY_VOLUME_NAME' &&
+    bl64_check_parameter 'MY_REPOSITORY_ID' &&
     s64_linux_lib_setup ||
     return $?
   bl64_msg_show_about
   bl64_msg_show_setup "$BL64_VAR_DEFAULT" \
-    'MY_VOLUME_NAME'
+    'MY_REPOSITORY_ID'
 }
 
-bl64_lib_script_version_set '1.0.3'
-bl64_msg_help_about_set 'Show dm-crypt device info'
+bl64_lib_script_version_set '1.0.0'
+bl64_msg_help_about_set 'Enable Linux native package repository'
 bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && my_initialize || exit $?
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
-s64_linux_lib_run_cryptsetup \
-  status \
-  "$MY_VOLUME_NAME"
+my_repo_enable "$MY_REPOSITORY_ID"
 bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
