real: promote 1.8.0 (#32)

diff --git a/src/linux-package/linux-repo-disable b/src/linux-package/linux-repo-disable
--- a/src/linux-package/linux-repo-disable
+++ b/src/linux-package/linux-repo-disable
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# template-one-base: 2.1.0
+# template-one: 3.2.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -17,27 +17,42 @@ declare S64_CORE_PATH_AT64="${HOME}/at64"
 [[ ! -d "$S64_CORE_PATH_AT64" ]] && S64_CORE_PATH_AT64='/opt'
 declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-${S64_CORE_PATH_AT64}/sysop64}"
 # shellcheck source-path=SCRIPTDIR/..
-source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/X_MODULE_X-lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
+source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/linux-lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
 # shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
-source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }
+source "${S64_CORE_PATH_BL64}/bashlib64-module-pkg.bash" &&
+  source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }
 
-# X_GLOBALS_PLACEHOLDER_X
+declare MY_REPOSITORY_ID="${1:-}"
 
-# X_FUNCTIONS_PLACEHOLDER_X
+function my_repo_disable_dnfv5() {
+  bl64_dbg_app_show_function "$@"
+  local repo="$1"
+  bl64_pkg_run_dnf config-manager setopt "$repo.enabled=0"
+}
+
+function my_repo_disable() {
+  bl64_dbg_app_show_function "$@"
+  local repo="$1"
+  case "$BL64_OS_DISTRO" in
+  ${BL64_OS_FD}-4?.*) my_repo_disable_dnfv5 "$repo" ;;
+  *) bl64_check_alert_unsupported ;;
+  esac
+}
 
 function my_initialize() {
   bl64_dbg_app_show_function
-  s64_X_MODULE_X_lib_setup ||
+  bl64_check_privilege_root &&
+    bl64_check_parameter 'MY_REPOSITORY_ID' &&
+    s64_linux_lib_setup ||
     return $?
-  # X_INIT_PLACEHOLDER_X
   bl64_msg_show_about
-  # X_INIT_INFO_PLACEHOLDER_X
+  bl64_msg_show_setup "$BL64_VAR_DEFAULT" \
+    'MY_REPOSITORY_ID'
 }
 
-# X_MAIN_PLACEHOLDER_X
 bl64_lib_script_version_set '1.0.0'
-bl64_msg_help_about_set 'X_HELP_ABOUT_X'
+bl64_msg_help_about_set 'Disable Linux native package repository'
 bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && my_initialize || exit $?
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
-# X_COMMAND_PLACEHOLDER_X
+my_repo_disable "$MY_REPOSITORY_ID"
 bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
