feat: update module

diff --git a/src/restic/restic-repo-create b/src/restic/restic-repo-create
--- a/src/restic/restic-repo-create
+++ b/src/restic/restic-repo-create
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
 # template: 1.0.0
+# template-import: 1.0.0
 #######################################
-# Linux / Dev / Crypt / Mount
+# Restic / Repo / Create
 #
 # Version: 1.0.0
 #
@@ -32,65 +33,33 @@ source "${SYSOP64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to loa
 source "${SYSOP64_CORE_PATH_BL64}/bashlib64-core.bash" ||
   { echo "Error: unable to load bashlib64" && exit 1; }
 # shellcheck source-path=SCRIPTDIR/..
-source "${SYSOP64_CORE_PATH_ROOT}/linux/linux-lib" || { echo "Error: unable to load module library" && exit 1; }
+source "${SYSOP64_CORE_PATH_ROOT}/restic/restic-lib" || { echo "Error: unable to load module library" && exit 1; }
 
 #
 # Functions
 #
 
-function luks_open() {
-  bl64_dbg_app_show_function "$@"
-  local device_path="${1:-}"
-  local volume_name="${2:-}"
-  bl64_msg_show_task "open luks device (${device_path} -> ${volume_name})"
-  linux_lib_run_cryptsetup \
-    luksOpen \
-    "$device_path" \
-    "$volume_name"
-}
-
-function fs_check() {
-  bl64_dbg_app_show_function "$@"
-  local volume_name="${1:-}"
-  bl64_msg_show_task "check filesystem (${volume_name})"
-  linux_lib_run_fsck \
-    "/dev/mapper/${volume_name}"
-}
-
-function fs_mount() {
-  bl64_dbg_app_show_function "$@"
-  local mount_point="${1:-}"
-  local volume_name="${2:-}"
-  bl64_msg_show_task "mount filesystem (${volume_name} -> ${mount_point})"
-  linux_lib_run_mount \
-    "/dev/mapper/${volume_name}" \
-    "$mount_point"
-}
-
 function initialize() {
   bl64_dbg_app_show_function
-  bl64_check_privilege_root &&
-    bl64_check_parameter 'device_path' &&
-    bl64_check_parameter 'mount_point' &&
-    linux_lib_setup
+  restic_lib_setup
 }
 
 #
 # Main
 #
 
-declare command='show'
+declare command='create'
 declare debug="$BL64_DBG_TARGET_NONE"
 declare verbose="$BL64_MSG_VERBOSE_ALL"
-declare device_path="${1:-}"
-declare mount_point="${2:-}"
-declare volume_name="${3:-}"
 
 bl64_dbg_set_level "$debug" && bl64_msg_set_level "$verbose" || exit $?
 initialize || exit $?
 
 bl64_msg_show_batch_start "$command"
-luks_open "$device_path" "$volume_name" &&
-  fs_check "$volume_name" &&
-  fs_mount "$mount_point" "$volume_name"
+bl64_msg_show_task "create restic repository (${SYSOP64_RESTIC_PATH_REPOSITORY})"
+restic_lib_run_restic \
+  init &&
+  bl64_msg_show_task "verify restic repository" &&
+  restic_lib_run_restic \
+    check
 bl64_msg_show_batch_finish $? "$command"
