feat: add  aws module (#5)

diff --git a/src/aws-eks/aws-eks-ami-info b/src/aws-eks/aws-eks-ami-info
--- a/src/aws-eks/aws-eks-ami-info
+++ b/src/aws-eks/aws-eks-ami-info
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 # Template: 1.0.0
 #######################################
-# PGSQL / Server / Lab / Control
+# AWS EKS / AMI / Info
 #
 # Version: 1.0.0
 #
@@ -29,40 +29,34 @@ declare SYSOP64_CORE_PATH_ROOT="${SYSOP64_CORE_PATH_ROOT:-/opt/sysop64}"
 # shellcheck source-path=SCRIPT_PATH
 source "${SYSOP64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
 # shellcheck source-path=lib/bl64
-source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-cnt.bash" &&
+source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
+  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
+  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-fs.bash" &&
+  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-aws.bash" &&
   source "${SYSOP64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo "Error: unable to load bashlib64" && exit 1; }
 # shellcheck source-path=SCRIPT_PATH
-source "${SYSOP64_CORE_PATH_ROOT}/pgsql/pgsql-lib" || { echo "Error: unable to load module library" && exit 1; }
+source "${SYSOP64_CORE_PATH_ROOT}/aws/aws-lib" || { echo "Error: unable to load module library" && exit 1; }
 
 #
 # Functions
 #
 
-function start() {
-  bl64_dbg_app_show_function
-  local container_port='5432'
-  bl64_msg_show_task 'start Postgresql Server in container mode'
-  bl64_cnt_run \
-    --name "$SYSOP64_PGSQL_SERVER_LAB_NAME" \
-    --env POSTGRES_PASSWORD="$SYSOP64_PGSQL_SERVER_LAB_PASSWORD" \
-    --detach \
-    --publish "$container_port:$container_port" \
-    postgres &&
-    bl64_msg_show_info "Starded container information
-Container Name: ${SYSOP64_PGSQL_SERVER_LAB_NAME}
-Password: ${SYSOP64_PGSQL_SERVER_LAB_PASSWORD}
-Port: ${container_port}"
-}
+function show_recommended() {
+  bl64_dbg_app_show_function "$@"
+  local ami_family="$1"
+  local k8s_version="$2"
+  local endpoint=''
 
-function stop() {
-  bl64_dbg_app_show_function
-  bl64_msg_show_task 'stop Postgresql Server running in container mode'
-  bl64_cnt_cli \
-    stop \
-    "$SYSOP64_PGSQL_SERVER_LAB_NAME" &&
-    bl64_cnt_cli \
-      rm \
-      "$SYSOP64_PGSQL_SERVER_LAB_NAME"
+  if [[ "$ami_family" == 'AL2' ]]; then
+    endpoint="$SYSOP64_AWS_API_EKS_AMI_AL2"
+  elif [[ "$ami_family" == 'AL2023' ]]; then
+    endpoint="$SYSOP64_AWS_API_EKS_AMI_AL2023_X86_64_STANDARD"
+  fi
+
+  bl64_aws_run_aws \
+    ssm get-parameter \
+    --name "/aws/service/eks/optimized-ami/${k8s_version}/${endpoint}/recommended/image_id" \
+    --query 'Parameter.Value'
 }
 
 function initialize() {
@@ -73,20 +67,21 @@ function initialize() {
   bl64_check_parameter 'command' ||
     { help && return 1; }
 
-  bl64_cnt_check_not_in_container &&
-    bl64_cnt_setup
+  bl64_aws_setup &&
+    aws_cli_access_check
 }
 
 function help() {
   bl64_msg_show_usage \
-    '-s|-o [-V Verbose] [-D Debug] [-h]' \
-    'PGSQL / Server / Lab / Control' \
+    '-l [-r Version] [-a Family] [-V Verbose] [-D Debug] [-h]' \
+    'AWS EKS / AMI / Info' \
     '
-    -s         : Start container and detach
-    -o         : Stop detached container
+    -l         : Show recommended AMI for EKS version
     ' '
     -h         : Show help
     ' '
+    -a Family  : AMI Family. Format: AL2|AL2023
+    -r Version : K8S version for the AMI. Format: X.Y
     -V Verbose : Set verbosity level. Format: one of BL64_MSG_VERBOSE_*
     -D Debug   : Enable debugging mode. Format: one of BL64_DBG_TARGET_*
     '
@@ -100,12 +95,15 @@ declare command="$BL64_VAR_NULL"
 declare debug="$BL64_DBG_TARGET_NONE"
 declare option=''
 declare verbose="$BL64_MSG_VERBOSE_ALL"
+declare ami_family='AL2023'
+declare k8s_version='1.29'
 
 (($# == 0)) && help && exit 1
-while getopts ':soV:D:h' option; do
+while getopts ':la:r:V:D:h' option; do
   case "$option" in
-  s) command='start' ;;
-  o) command='stop' ;;
+  l) command='show_recommended' ;;
+  a) ami_family="$OPTARG" ;;
+  r) k8s_version="$OPTARG" ;;
   V) verbose="$OPTARG" ;;
   D) debug="$OPTARG" ;;
   h) help && exit 0 ;;
@@ -116,5 +114,5 @@ bl64_dbg_set_level "$debug" && bl64_msg_set_level "$verbose" || exit $?
 initialize "$command" || exit $?
 
 bl64_msg_show_batch_start "$command"
-"${command}"
+"${command}" "$ami_family" "$k8s_version"
 bl64_msg_show_batch_finish $? "$command"
diff --git a/src/pgsql/pgsql-query-info b/src/pgsql/pgsql-query-info
--- a/src/pgsql/pgsql-query-info
+++ b/src/pgsql/pgsql-query-info
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 # Template: 1.0.0
 #######################################
-# GitHub / Repo / Show
+# PGSQL / Query / Info
 #
-# Version: 1.0.1
+# Version: 1.0.0
 #
 #######################################
 # Copyright [2024] [serdigital64@gmail.com]
@@ -31,54 +31,80 @@ source "${SYSOP64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to loa
 # shellcheck source-path=lib/bl64
 source "${SYSOP64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo "Error: unable to load bashlib64" && exit 1; }
 # shellcheck source-path=SCRIPT_PATH
-source "${SYSOP64_CORE_PATH_ROOT}/github/github-lib" || { echo "Error: unable to load module library" && exit 1; }
+source "${SYSOP64_CORE_PATH_ROOT}/pgsql/pgsql-lib" || { echo "Error: unable to load module library" && exit 1; }
 
 #
 # Globals
 #
 
+export PGPASSWORD
+export PSQL_PAGER=''
+
 #
 # Functions
 #
 
-function show() {
+function show_active() {
   bl64_dbg_app_show_function
-  local owner="$1"
-  local repository="$2"
-  local api_prefix="repos/${owner}/${repository}"
-
-  bl64_msg_show_info 'branch protection'
-  github_lib_cli_run api "${api_prefix}"
+  printf "
+    SELECT
+      datname,
+      usename,
+      backend_type,
+      query_id,
+      query_start,
+      now(),
+      now() - query_start as elapsed,
+      query
+    FROM
+      pg_stat_activity
+    WHERE
+      state = 'active'
+    ORDER BY
+      datname,
+      usename,
+      backend_type,
+      query_id,
+      query_start;
+  " |
+  "$SYSOP64_PGSQL_CLI_PATH" \
+    --host="$SYSOP64_PGSQL_SERVER_HOST" \
+    --port="$SYSOP64_PGSQL_SERVER_PORT" \
+    --dbname="$SYSOP64_PGSQL_DB_NAME" \
+    --username="$SYSOP64_PGSQL_SERVER_USER" \
+    --file='-'
 }
 
 function initialize() {
   bl64_dbg_app_show_function "$@"
   # shellcheck disable=SC2034
   local command="$1"
-  local owner="$2"
-  local repository="$3"
 
-  bl64_check_parameter 'owner' &&
-    bl64_check_parameter 'repository' &&
-    bl64_check_parameter 'command' ||
+  bl64_check_parameter 'command' ||
     { help && return 1; }
 
-  return 0
+  bl64_check_command "$SYSOP64_PGSQL_CLI_PATH" &&
+    bl64_check_export 'SYSOP64_PGSQL_SERVER_PASSWORD' ||
+    return $?
+
+  PGPASSWORD="$SYSOP64_PGSQL_SERVER_PASSWORD"
 }
 
 function help() {
   bl64_msg_show_usage \
-    '-s -o Owner -r Repository [-V Verbose] [-D Debug] [-h]' \
-    'GitHub / Repo / Show' \
+    '-a [-o Host] [-p Port] [-u User] [-b DB] [-V Verbose] [-D Debug] [-h]' \
+    'PGSQL / Query / Info' \
     '
-    -s           : Show repository settings
+    -a         : Show active
     ' '
-    -h           : Show help
+    -o Host    : Host FQDN. Alternative shell-env: SYSOP64_PGSQL_SERVER_HOST  
+    -p Port    : DB Port. Alternative shell-ehv: SYSOP64_PGSQL_SERVER_PORT 
+    -u User    : DB User. Alternative shell-ehv: SYSOP64_PGSQL_SERVER_USER 
+    -b DB      : DB Name. Alternative shell-ehv: SYSOP64_PGSQL_DB_NAME
+    -h         : Show help
     ' '
-    -o Owner     : user or organization
-    -r Repository: repository name
-    -V Verbose   : Set verbosity level. Format: one of BL64_MSG_VERBOSE_*
-    -D Debug     : Enable debugging mode. Format: one of BL64_DBG_TARGET_*
+    -V Verbose : Set verbosity level. Format: one of BL64_MSG_VERBOSE_*
+    -D Debug   : Enable debugging mode. Format: one of BL64_DBG_TARGET_*
     '
 }
 
@@ -90,15 +116,15 @@ declare command="$BL64_VAR_NULL"
 declare debug="$BL64_DBG_TARGET_NONE"
 declare option=''
 declare verbose="$BL64_MSG_VERBOSE_ALL"
-declare owner=''
-declare repository=''
 
 (($# == 0)) && help && exit 1
-while getopts ':so:r:V:D:h' option; do
+while getopts ':ao:p:u:b:V:D:h' option; do
   case "$option" in
-  s) command='show' ;;
-  o) owner="$OPTARG" ;;
-  r) repository="$OPTARG" ;;
+  a) command='show_active' ;;
+  o) SYSOP64_PGSQL_SERVER_HOST="$OPTARG" ;;
+  p) SYSOP64_PGSQL_SERVER_PORT="$OPTARG" ;;
+  u) SYSOP64_PGSQL_SERVER_USER="$OPTARG" ;;
+  b) SYSOP64_PGSQL_DB_NAME="$OPTARG" ;;
   V) verbose="$OPTARG" ;;
   D) debug="$OPTARG" ;;
   h) help && exit 0 ;;
@@ -106,8 +132,8 @@ while getopts ':so:r:V:D:h' option; do
   esac
 done
 bl64_dbg_set_level "$debug" && bl64_msg_set_level "$verbose" || exit $?
-initialize "$command" "$owner" "$repository" || exit $?
+initialize "$command" || exit $?
 
 bl64_msg_show_batch_start "$command"
-"$command" "$owner" "$repository" ;;
+"${command}"
 bl64_msg_show_batch_finish $? "$command"
diff --git a/src/pgsql/pgsql-table-info b/src/pgsql/pgsql-table-info
--- a/src/pgsql/pgsql-table-info
+++ b/src/pgsql/pgsql-table-info
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 # Template: 1.0.0
 #######################################
-# PGSQL / Server / Lab / Control
+# PGSQL / Table / Info
 #
 # Version: 1.0.0
 #
@@ -29,62 +29,77 @@ declare SYSOP64_CORE_PATH_ROOT="${SYSOP64_CORE_PATH_ROOT:-/opt/sysop64}"
 # shellcheck source-path=SCRIPT_PATH
 source "${SYSOP64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
 # shellcheck source-path=lib/bl64
-source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-cnt.bash" &&
-  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo "Error: unable to load bashlib64" && exit 1; }
+source "${SYSOP64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo "Error: unable to load bashlib64" && exit 1; }
 # shellcheck source-path=SCRIPT_PATH
 source "${SYSOP64_CORE_PATH_ROOT}/pgsql/pgsql-lib" || { echo "Error: unable to load module library" && exit 1; }
+
+#
+# Globals
+#
+
+export PGPASSWORD
+export PSQL_PAGER=''
 
 #
 # Functions
 #
 
-function start() {
-  bl64_dbg_app_show_function
-  local container_port='5432'
-  bl64_msg_show_task 'start Postgresql Server in container mode'
-  bl64_cnt_run \
-    --name "$SYSOP64_PGSQL_SERVER_LAB_NAME" \
-    --env POSTGRES_PASSWORD="$SYSOP64_PGSQL_SERVER_LAB_PASSWORD" \
-    --detach \
-    --publish "$container_port:$container_port" \
-    postgres &&
-    bl64_msg_show_info "Starded container information
-Container Name: ${SYSOP64_PGSQL_SERVER_LAB_NAME}
-Password: ${SYSOP64_PGSQL_SERVER_LAB_PASSWORD}
-Port: ${container_port}"
+function list() {
+  bl64_dbg_app_show_function "$@"
+  local table="$1"
+  "$SYSOP64_PGSQL_CLI_PATH" \
+    --host="$SYSOP64_PGSQL_SERVER_HOST" \
+    --port="$SYSOP64_PGSQL_SERVER_PORT" \
+    --dbname="$SYSOP64_PGSQL_DB_NAME" \
+    --username="$SYSOP64_PGSQL_SERVER_USER" \
+    --command="\\dt"
 }
 
-function stop() {
-  bl64_dbg_app_show_function
-  bl64_msg_show_task 'stop Postgresql Server running in container mode'
-  bl64_cnt_cli \
-    stop \
-    "$SYSOP64_PGSQL_SERVER_LAB_NAME" &&
-    bl64_cnt_cli \
-      rm \
-      "$SYSOP64_PGSQL_SERVER_LAB_NAME"
+function describe() {
+  bl64_dbg_app_show_function "$@"
+  local table="$1"
+  "$SYSOP64_PGSQL_CLI_PATH" \
+    --host="$SYSOP64_PGSQL_SERVER_HOST" \
+    --port="$SYSOP64_PGSQL_SERVER_PORT" \
+    --dbname="$SYSOP64_PGSQL_DB_NAME" \
+    --username="$SYSOP64_PGSQL_SERVER_USER" \
+    --command="\\d $table"
 }
 
 function initialize() {
   bl64_dbg_app_show_function "$@"
   # shellcheck disable=SC2034
   local command="$1"
+  local table="$2"
 
   bl64_check_parameter 'command' ||
     { help && return 1; }
 
-  bl64_cnt_check_not_in_container &&
-    bl64_cnt_setup
+  bl64_check_command "$SYSOP64_PGSQL_CLI_PATH" &&
+    bl64_check_export 'SYSOP64_PGSQL_SERVER_PASSWORD' ||
+    return $?
+
+  if [[ "$command" == 'describe' ]]; then
+    bl64_check_parameter 'table' ||
+      return $?
+  fi
+
+  PGPASSWORD="$SYSOP64_PGSQL_SERVER_PASSWORD"
 }
 
 function help() {
   bl64_msg_show_usage \
-    '-s|-o [-V Verbose] [-D Debug] [-h]' \
-    'PGSQL / Server / Lab / Control' \
+    '-l|-e [-o Host] [-p Port] [-u User] [-b DB] [-t Table] [-V Verbose] [-D Debug] [-h]' \
+    'PGSQL / Table / Info' \
     '
-    -s         : Start container and detach
-    -o         : Stop detached container
+    -l         : List tables
+    -e         : Describe table
     ' '
+    -o Host    : Host FQDN. Alternative shell-env: SYSOP64_PGSQL_SERVER_HOST  
+    -p Port    : DB Port. Alternative shell-ehv: SYSOP64_PGSQL_SERVER_PORT 
+    -u User    : DB User. Alternative shell-ehv: SYSOP64_PGSQL_SERVER_USER 
+    -b DB      : DB Name. Alternative shell-ehv: SYSOP64_PGSQL_DB_NAME
+    -t Table   : DB Table.
     -h         : Show help
     ' '
     -V Verbose : Set verbosity level. Format: one of BL64_MSG_VERBOSE_*
@@ -100,12 +115,18 @@ declare command="$BL64_VAR_NULL"
 declare debug="$BL64_DBG_TARGET_NONE"
 declare option=''
 declare verbose="$BL64_MSG_VERBOSE_ALL"
+declare table="$BL64_VAR_DEFAULT"
 
 (($# == 0)) && help && exit 1
-while getopts ':soV:D:h' option; do
+while getopts ':leo:p:u:b:t:V:D:h' option; do
   case "$option" in
-  s) command='start' ;;
-  o) command='stop' ;;
+  l) command='list' ;;
+  e) command='describe' ;;
+  o) SYSOP64_PGSQL_SERVER_HOST="$OPTARG" ;;
+  p) SYSOP64_PGSQL_SERVER_PORT="$OPTARG" ;;
+  u) SYSOP64_PGSQL_SERVER_USER="$OPTARG" ;;
+  b) SYSOP64_PGSQL_DB_NAME="$OPTARG" ;;
+  t) table="$OPTARG" ;;
   V) verbose="$OPTARG" ;;
   D) debug="$OPTARG" ;;
   h) help && exit 0 ;;
@@ -113,8 +134,8 @@ while getopts ':soV:D:h' option; do
   esac
 done
 bl64_dbg_set_level "$debug" && bl64_msg_set_level "$verbose" || exit $?
-initialize "$command" || exit $?
+initialize "$command" "$table" || exit $?
 
 bl64_msg_show_batch_start "$command"
-"${command}"
+"${command}" "$table"
 bl64_msg_show_batch_finish $? "$command"
